// packages/react/src/ui/Crosshair.tsx
import { useChartInstance } from '../context';
import { useCrosshairPosition } from '../store-bridge';

import { formatTime } from '@wick-charts/core';

export function Crosshair() {
  const chart = useChartInstance();
  const position = useCrosshairPosition(chart);

  if (!position) return null;

  const theme = chart.getTheme();
  const dataInterval = chart.getDataInterval();

  const labelStyle = {
    background: theme.crosshair.labelBackground,
    color: theme.crosshair.labelTextColor,
    fontSize: theme.typography.axisFontSize,
    fontFamily: theme.typography.fontFamily,
    padding: '2px 6px',
    borderRadius: 2,
    whiteSpace: 'nowrap' as const,
    pointerEvents: 'none' as const,
  };

  return (
    <>
      {/* Y label on right axis */}
      <div
        style={{
          position: 'absolute',
          right: 0,
          top: position.mediaY,
          transform: 'translateY(-50%)',
          ...labelStyle,
        }}
      >
        {chart.yScale.formatY(position.y)}
      </div>
      {/* Time label on bottom axis */}
      <div
        style={{
          position: 'absolute',
          bottom: 0,
          left: position.mediaX,
          transform: 'translateX(-50%)',
          ...labelStyle,
        }}
      >
        {formatTime(position.time, dataInterval)}
      </div>
    </>
  );
}

// packages/vue/src/ui/Crosshair.vue
<script setup lang="ts">
import { formatTime } from '@wick-charts/core';
import { computed } from 'vue';

import { useCrosshairPosition } from '../composables';
import { useChartInstance } from '../context';

const chart = useChartInstance();
const position = useCrosshairPosition(chart);

const theme = computed(() => chart.getTheme());
const dataInterval = computed(() => chart.getDataInterval());

const labelStyle = computed(() => ({
  background: theme.value.crosshair.labelBackground,
  color: theme.value.crosshair.labelTextColor,
  fontSize: theme.value.typography.axisFontSize + 'px',
  fontFamily: theme.value.typography.fontFamily,
  padding: '2px 6px',
  borderRadius: '2px',
  whiteSpace: 'nowrap' as const,
  pointerEvents: 'none' as const,
}));
</script>

<template>
  <template v-if="position">
    <!-- Y label on right axis -->
    <div
      :style="{
        position: 'absolute',
        right: '0',
        top: position.mediaY + 'px',
        transform: 'translateY(-50%)',
        ...labelStyle,
      }"
    >
      {{ chart.yScale.formatY(position.y) }}
    </div>
    <!-- Time label on bottom axis -->
    <div
      :style="{
        position: 'absolute',
        bottom: '0',
        left: position.mediaX + 'px',
        transform: 'translateX(-50%)',
        ...labelStyle,
      }"
    >
      {{ formatTime(position.time, dataInterval) }}
    </div>
  </template>
</template>
