// packages/react/src/ui/InfoBar.tsx
import { type ReactNode, useLayoutEffect, useState } from 'react';

import {
  type OHLCData,
  type SeriesSnapshot,
  type TimePoint,
  type TooltipFormatter,
  buildHoverSnapshots,
  buildLastSnapshots,
  formatCompact,
  formatPriceAdaptive,
  formatTime,
  resolveCandlestickBodyColor,
} from '@wick-charts/core';

import { useChartInstance } from '../context';
import { useCrosshairPosition } from '../store-bridge';
import { useTheme } from '../ThemeContext';
import type { TooltipSort } from './Tooltip';

/** Context passed to the {@link InfoBar} render-prop. */
export interface InfoBarRenderContext {
  readonly snapshots: readonly SeriesSnapshot[];
  /** Timestamp displayed. In hover mode it's the crosshair time; in last-mode it's the newest point. */
  readonly time: number;
  /** `true` while the user's pointer is over the chart (hover mode). */
  readonly isHover: boolean;
}

/** Props for the {@link InfoBar} component. */
export interface InfoBarProps {
  /** Sort order for line values (default: 'none'). */
  sort?: TooltipSort;
  /**
   * Custom formatter for every displayed number in the default UI. Called per
   * cell with the field hint (`'open' | 'high' | 'low' | 'close' | 'volume' | 'value'`).
   * Defaults: adaptive precision for ohlc/value, compact (K/M/B/T) for volume.
   * Ignored when {@link children} is a render-prop.
   */
  format?: TooltipFormatter;
  /**
   * Render-prop escape hatch. Receives the computed snapshots and replaces the
   * entire built-in layout. Filter, reorder, or re-style rows here without
   * re-implementing any data wiring.
   */
  children?: (ctx: InfoBarRenderContext) => ReactNode;
}

/** Default InfoBar formatter — adaptive for ohlc/value, compact for volume. */
const defaultInfoBarFormat: TooltipFormatter = (v, field) =>
  field === 'volume' ? formatCompact(v) : formatPriceAdaptive(v);

/**
 * Compact OHLC/series info bar rendered as a flex row above the chart canvas.
 * Pairs with {@link Tooltip} (which then only renders its floating near-cursor part).
 *
 * Pass a render-prop child for a custom layout — the built-in UI is used when
 * {@link children} is omitted.
 */
export function InfoBar({ sort = 'none', format = defaultInfoBarFormat, children }: InfoBarProps) {
  const chart = useChartInstance();
  const theme = useTheme();
  const crosshair = useCrosshairPosition(chart);

  const [, bump] = useState(0);
  useLayoutEffect(() => {
    const onOverlayChange = () => bump((n) => n + 1);
    chart.on('overlayChange', onOverlayChange);
    // Catch-up: a sibling series' layout effect may have registered data in
    // the same commit. Bump so the next synchronous render picks it up.
    if (chart.getSeriesIds().length > 0) bump((n) => n + 1);

    return () => {
      chart.off('overlayChange', onOverlayChange);
    };
  }, [chart]);

  // Hover-over-the-y-axis gap: the overlay canvas includes the y-axis strip,
  // so a crosshair event fires for offsets past the plotted data. The
  // nearest-time lookup then snaps to an out-of-range timestamp and returns
  // no samples. Falling back to the last-mode snapshots here keeps the bar
  // populated (showing last values at 0.6 opacity) instead of blinking out
  // every time the pointer grazes the y-axis.
  const lastSnapshots = buildLastSnapshots(chart, { sort, cacheKey: 'infobar-last' });
  let snapshots = lastSnapshots;
  let displayTime = lastSnapshots.length === 0 ? 0 : Math.max(...lastSnapshots.map((s) => s.data.time));
  let isHover = false;
  if (crosshair !== null) {
    const hoverSnapshots = buildHoverSnapshots(chart, { time: crosshair.time, sort, cacheKey: 'infobar-hover' });
    if (hoverSnapshots.length > 0) {
      snapshots = hoverSnapshots;
      // `snapshots[0].data.time` is index-0 → shifts when `sort` reorders.
      // Use the raw crosshair time (what the user is pointing at) so the
      // header stays stable across sort toggles.
      displayTime = crosshair.time;
      isHover = true;
    }
  }

  if (snapshots.length === 0) return null;

  if (children) {
    return (
      <div
        data-tooltip-legend=""
        style={{
          display: 'flex',
          alignItems: 'center',
          flexShrink: 0,
          fontFamily: theme.typography.fontFamily,
          fontSize: theme.typography.fontSize,
          fontVariantNumeric: 'tabular-nums',
          opacity: isHover ? 1 : 0.6,
          transition: 'opacity 0.2s ease',
          pointerEvents: 'none',
        }}
      >
        {children({ snapshots, time: displayTime, isHover })}
      </div>
    );
  }

  const dataInterval = chart.getDataInterval();

  return (
    <div
      data-tooltip-legend=""
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        flexWrap: 'wrap',
        padding: '4px 8px',
        flexShrink: 0,
        fontSize: theme.typography.fontSize,
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        opacity: isHover ? 1 : 0.6,
        transition: 'opacity 0.2s ease',
        pointerEvents: 'none',
      }}
    >
      <span style={{ color: theme.axis.textColor, marginRight: 2 }}>{formatTime(displayTime, dataInterval)}</span>
      {snapshots.map((s) => {
        const isOHLC = 'open' in s.data;
        if (isOHLC) {
          const ohlc = s.data as OHLCData;
          const isUp = ohlc.close >= ohlc.open;
          const c = resolveCandlestickBodyColor(isUp ? theme.candlestick.up.body : theme.candlestick.down.body);
          return (
            <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
              <LegendItem label="O" display={format(ohlc.open, 'open')} color={c} dim={theme.axis.textColor} />
              <LegendItem label="H" display={format(ohlc.high, 'high')} color={c} dim={theme.axis.textColor} />
              <LegendItem label="L" display={format(ohlc.low, 'low')} color={c} dim={theme.axis.textColor} />
              <LegendItem label="C" display={format(ohlc.close, 'close')} color={c} dim={theme.axis.textColor} />
              {ohlc.volume != null && (
                <LegendItem
                  label="V"
                  display={format(ohlc.volume, 'volume')}
                  color={theme.axis.textColor}
                  dim={theme.axis.textColor}
                />
              )}
            </span>
          );
        }
        const line = s.data as TimePoint;

        return (
          <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 3 }}>
            <span
              style={{
                width: 6,
                height: 6,
                borderRadius: '50%',
                background: s.color,
                flexShrink: 0,
              }}
            />
            <span style={{ color: s.color, fontWeight: 500 }}>{format(line.value, 'value')}</span>
          </span>
        );
      })}
    </div>
  );
}

function LegendItem({ label, display, color, dim }: { label: string; display: string; color: string; dim: string }) {
  return (
    <>
      <span style={{ color: dim, opacity: 0.5, marginLeft: 5 }}>{label}</span>
      <span style={{ color, fontWeight: 500, marginLeft: 2 }}>{display}</span>
    </>
  );
}

// packages/vue/src/ui/InfoBar.vue
<script setup lang="ts">
import {
  type OHLCData,
  type SeriesSnapshot,
  type SnapshotSort,
  type TimePoint,
  type TooltipFormatter,
  buildHoverSnapshots,
  buildLastSnapshots,
  formatCompact,
  formatPriceAdaptive,
  formatTime,
  resolveCandlestickBodyColor,
} from '@wick-charts/core';
import { computed, inject, onMounted, onUnmounted, ref, useSlots } from 'vue';

import { useCrosshairPosition } from '../composables';
import { InfoBarAnchorKey, ThemeKey, useChartInstance } from '../context';

const props = defineProps<{
  sort?: SnapshotSort;
  format?: TooltipFormatter;
}>();

defineSlots<{
  default?(ctx: { snapshots: readonly SeriesSnapshot[]; time: number; isHover: boolean }): unknown;
}>();

// Use computed fallbacks — `withDefaults` is inconsistent for function props.
const effectiveSort = computed<SnapshotSort>(() => props.sort ?? 'none');
const effectiveFormat = computed<TooltipFormatter>(
  () =>
    props.format ?? ((v: number, field: string) => (field === 'volume' ? formatCompact(v) : formatPriceAdaptive(v))),
);

const chart = useChartInstance();
const crosshair = useCrosshairPosition(chart);
const theme = inject(ThemeKey);
const anchor = inject(InfoBarAnchorKey);

// Match the "loud failure" contract of other Vue overlays — misuse outside
// `<ChartContainer>` should throw rather than render nothing silently.
if (!theme) {
  throw new Error('<InfoBar> must be used within <ChartContainer>: missing ThemeKey.');
}
if (!anchor) {
  throw new Error('<InfoBar> must be used within <ChartContainer>: missing InfoBarAnchorKey.');
}

// `bump` re-runs computed values after any overlay-relevant mutation
// (dataUpdate / seriesChange / setSeriesVisible / setTheme / option changes).
const bump = ref(0);
const onOverlayChange = () => {
  bump.value++;
};
onMounted(() => {
  chart.on('overlayChange', onOverlayChange);
  // Catch-up: a sibling series' mount effect may have registered data in the
  // same synchronous flush, so poke the computed now.
  if (chart.getSeriesIds().length > 0) bump.value++;
});
onUnmounted(() => {
  chart.off('overlayChange', onOverlayChange);
});

// Hover-over-the-y-axis gap: the overlay canvas includes the y-axis strip,
// so a crosshair event fires for offsets past the plotted data. The
// nearest-time lookup then snaps to an out-of-range timestamp and returns
// no samples. Falling back to the last-mode snapshots keeps the bar
// populated (showing last values at 0.6 opacity) instead of blinking out
// every time the pointer grazes the y-axis.
const hoverSnapshots = computed<readonly SeriesSnapshot[] | null>(() => {
  void bump.value;
  const pos = crosshair.value;
  if (pos === null) return null;

  return buildHoverSnapshots(chart, { time: pos.time, sort: effectiveSort.value, cacheKey: 'infobar-hover' });
});

const lastSnapshots = computed<readonly SeriesSnapshot[]>(() => {
  void bump.value;

  return buildLastSnapshots(chart, { sort: effectiveSort.value, cacheKey: 'infobar-last' });
});

const isHover = computed(() => hoverSnapshots.value !== null && hoverSnapshots.value.length > 0);
const snapshots = computed<readonly SeriesSnapshot[]>(() =>
  isHover.value ? (hoverSnapshots.value as readonly SeriesSnapshot[]) : lastSnapshots.value,
);

const dataInterval = computed(() => chart.getDataInterval());
const displayTime = computed(() => {
  if (snapshots.value.length === 0) return 0;
  if (isHover.value && crosshair.value) return crosshair.value.time;

  return Math.max(...snapshots.value.map((s) => s.data.time));
});

const slots = useSlots();
const hasCustomSlot = computed(() => typeof slots.default === 'function');

function isOHLC(data: OHLCData | TimePoint): data is OHLCData {
  return 'open' in data;
}
</script>

<template>
  <Teleport v-if="anchor && theme && snapshots.length > 0" :to="anchor">
    <div
      data-tooltip-legend=""
      :style="
        hasCustomSlot
          ? {
              display: 'flex',
              alignItems: 'center',
              flexShrink: 0,
              fontSize: theme.typography.fontSize + 'px',
              fontFamily: theme.typography.fontFamily,
              fontVariantNumeric: 'tabular-nums',
              opacity: isHover ? 1 : 0.6,
              transition: 'opacity 0.2s ease',
              pointerEvents: 'none',
            }
          : {
              display: 'flex',
              alignItems: 'center',
              gap: '4px',
              flexWrap: 'wrap',
              padding: '4px 8px',
              flexShrink: 0,
              fontSize: theme.typography.fontSize + 'px',
              fontFamily: theme.typography.fontFamily,
              fontVariantNumeric: 'tabular-nums',
              opacity: isHover ? 1 : 0.6,
              transition: 'opacity 0.2s ease',
              pointerEvents: 'none',
            }
      "
    >
      <slot v-if="hasCustomSlot" :snapshots="snapshots" :time="displayTime" :is-hover="isHover" />
      <template v-else>
        <span :style="{ color: theme.axis.textColor, marginRight: '2px' }">
          {{ formatTime(displayTime, dataInterval) }}
        </span>
        <template v-for="s in snapshots" :key="s.id">
          <span v-if="isOHLC(s.data)" :style="{ display: 'inline-flex', alignItems: 'center', gap: '4px' }">
            <template
              v-for="cell in [
                { label: 'O', field: 'open' as const, val: (s.data as OHLCData).open },
                { label: 'H', field: 'high' as const, val: (s.data as OHLCData).high },
                { label: 'L', field: 'low' as const, val: (s.data as OHLCData).low },
                { label: 'C', field: 'close' as const, val: (s.data as OHLCData).close },
              ]"
              :key="cell.label"
            >
              <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">{{ cell.label }}</span>
              <span
                :style="{
                  color: resolveCandlestickBodyColor(
                    (s.data as OHLCData).close >= (s.data as OHLCData).open
                      ? theme.candlestick.up.body
                      : theme.candlestick.down.body,
                  ),
                  fontWeight: 500,
                  marginLeft: '2px',
                }"
              >
                {{ effectiveFormat(cell.val, cell.field) }}
              </span>
            </template>
            <template v-if="(s.data as OHLCData).volume != null">
              <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">V</span>
              <span :style="{ color: theme.axis.textColor, fontWeight: 500, marginLeft: '2px' }">
                {{ effectiveFormat((s.data as OHLCData).volume!, 'volume') }}
              </span>
            </template>
          </span>
          <span v-else :style="{ display: 'inline-flex', alignItems: 'center', gap: '3px' }">
            <span
              :style="{
                width: '6px',
                height: '6px',
                borderRadius: '50%',
                background: s.color,
                flexShrink: 0,
              }"
            />
            <span :style="{ color: s.color, fontWeight: 500 }">
              {{ effectiveFormat((s.data as TimePoint).value, 'value') }}
            </span>
          </span>
        </template>
      </template>
    </div>
  </Teleport>
</template>
