// packages/svelte/src/ui/Legend.svelte
<script context="module" lang="ts">
/**
 * Minimal visual shape the `items` override accepts — just what the built-in
 * swatch/label UI needs. The canonical `LegendItem` (re-exported from
 * `@wick-charts/core`) carries identity plus `toggle`/`isolate` closures;
 * those aren't meaningful for a pre-baked, non-interactive legend.
 */
export interface LegendItemOverride {
  label: string;
  color: string;
}

/** Payload for `onToggle` — one entry per user click, regardless of built-in vs custom rendering. */
export interface LegendToggleInfo {
  /** The clicked item's id (matches `LegendItem.id`). */
  id: string;
  /** Which interaction produced this change. */
  action: 'toggle' | 'isolate' | 'unisolate';
}
</script>

<script lang="ts">
  import type { ChartInstance, LegendItem } from '@wick-charts/core';
  import { onDestroy } from 'svelte';

  import { getChartContext, getLegendAnchor, getLegendRightAnchor, getThemeContext } from '../context';
  import { portal } from './portal';

  type LegendMode = 'toggle' | 'isolate' | 'solo';

  export let items: LegendItemOverride[] | undefined = undefined;
  export let position: 'bottom' | 'right' = 'bottom';
  /** `'isolate'` shows only the clicked item; `'solo'` is a @deprecated alias. */
  export let mode: LegendMode = 'toggle';
  /** Fired after a click changes series visibility — via the built-in UI or a custom slot calling `item.toggle()`/`isolate()` directly. */
  export let onToggle: ((info: LegendToggleInfo) => void) | undefined = undefined;

  const chartStore = getChartContext();
  const themeStore = getThemeContext();
  const bottomAnchorStore = getLegendAnchor();
  const rightAnchorStore = getLegendRightAnchor();

  let isolatedId: string | null = null;
  let bump = 0;
  let overlayUnsub: (() => void) | null = null;
  let seriesChangeUnsub: (() => void) | null = null;

  $: {
    const c = $chartStore;
    if (c && !overlayUnsub) {
      const onOverlay = () => {
        bump++;
      };
      const onSeries = () => {
        isolatedId = null;
      };
      c.on('overlayChange', onOverlay);
      c.on('seriesChange', onSeries);
      overlayUnsub = () => c.off('overlayChange', onOverlay);
      seriesChangeUnsub = () => c.off('seriesChange', onSeries);
      if (c.getSeriesIds().length > 0) bump++;
    }
  }

  onDestroy(() => {
    overlayUnsub?.();
    seriesChangeUnsub?.();
  });

  $: chart = $chartStore;
  $: theme = $themeStore;
  $: anchor = position === 'right' ? $rightAnchorStore : $bottomAnchorStore;

  interface MakeItemArgs {
    id: string;
    seriesId: string;
    layerIndex: number | undefined;
    label: string;
    color: string;
    isDisabled: boolean;
  }

  function makeItem(c: ChartInstance, args: MakeItemArgs): LegendItem {
    const { id, seriesId, layerIndex, label, color, isDisabled } = args;

    const toggle = () => {
      if (layerIndex !== undefined) {
        c.setLayerVisible(seriesId, layerIndex, !c.isLayerVisible(seriesId, layerIndex));
      } else {
        c.setSeriesVisible(seriesId, !c.isSeriesVisible(seriesId));
      }
      onToggle?.({ id, action: 'toggle' });
    };

    // Read `isolatedId` live — closing over the component-level `let`, not a
    // captured-at-build-time snapshot. Without this, back-to-back
    // `item.isolate()` calls from the slot (before Svelte flushes a
    // re-render) would see a stale null and keep re-isolating instead of
    // restoring all series on the second click.
    const isolate = () => {
      if (isolatedId === id) {
        c.batch(() => {
          for (const sid of c.getSeriesIds()) {
            c.setSeriesVisible(sid, true);
            const layers = c.getSeriesLayers(sid);
            if (layers) {
              for (let i = 0; i < layers.length; i++) c.setLayerVisible(sid, i, true);
            }
          }
        });
        isolatedId = null;
        onToggle?.({ id, action: 'unisolate' });

        return;
      }

      c.batch(() => {
        for (const sid of c.getSeriesIds()) {
          const layers = c.getSeriesLayers(sid);
          if (layers) {
            c.setSeriesVisible(sid, sid === seriesId);
            for (let i = 0; i < layers.length; i++) {
              c.setLayerVisible(sid, i, sid === seriesId && i === layerIndex);
            }
          } else {
            c.setSeriesVisible(sid, sid === id);
          }
        }
      });
      isolatedId = id;
      onToggle?.({ id, action: 'isolate' });
    };

    return { id, seriesId, layerIndex, label, color, isDisabled, toggle, isolate };
  }

  function buildLegendItems(
    c: ChartInstance | undefined,
    _bumpDep: number,
    _isolatedDep: string | null,
  ): LegendItem[] {
    void _bumpDep;
    void _isolatedDep;
    if (!c) return [];

    const result: LegendItem[] = [];
    for (const seriesId of c.getSeriesIds()) {
      const layers = c.getSeriesLayers(seriesId);
      if (layers) {
        for (let layerIndex = 0; layerIndex < layers.length; layerIndex++) {
          const id = `${seriesId}_layer${layerIndex}`;
          const visible = c.isSeriesVisible(seriesId) && c.isLayerVisible(seriesId, layerIndex);
          result.push(
            makeItem(c, {
              id,
              seriesId,
              layerIndex,
              label: c.getLayerLabel(seriesId, layerIndex) ?? `Series ${layerIndex + 1}`,
              color: layers[layerIndex].color,
              isDisabled: !visible,
            }),
          );
        }
      } else {
        const color = c.getSeriesColor(seriesId);
        if (!color) continue;

        const label = c.getSeriesLabel(seriesId);
        const visible = c.isSeriesVisible(seriesId);
        result.push(
          makeItem(c, {
            id: seriesId,
            seriesId,
            layerIndex: undefined,
            label: label ?? 'Series',
            color,
            isDisabled: !visible,
          }),
        );
      }
    }

    return result;
  }

  // `isolatedId` is in the dep list so the list rebuilds when isolate state
  // changes (refreshes `isDisabled` via chart visibility reads).
  $: legendItems = buildLegendItems(chart, bump, isolatedId);

  function handleClick(item: LegendItem) {
    if (mode === 'isolate' || mode === 'solo') item.isolate();
    else item.toggle();
  }
</script>

{#if anchor && theme}
  {#if $$slots.default && legendItems.length > 0}
    <div
      use:portal={anchor}
      data-legend={position}
      style="display:flex;flex-direction:{position === 'right'
        ? 'column'
        : 'row'};flex-wrap:wrap;gap:{position === 'right'
        ? '6px'
        : '14px'};padding:{position === 'right'
        ? '8px 6px'
        : '6px 8px'};align-items:{position === 'right'
        ? 'flex-start'
        : 'center'};justify-content:{position === 'right'
        ? 'flex-start'
        : 'center'};font-family:{theme.typography.fontFamily};font-size:{theme.axis.fontSize}px;color:{theme.axis.textColor};pointer-events:auto;flex-shrink:0;"
    >
      <slot items={legendItems} />
    </div>
  {:else if items && items.length > 0}
    <div
      use:portal={anchor}
      data-legend={position}
      style="display:flex;flex-direction:{position === 'right'
        ? 'column'
        : 'row'};flex-wrap:wrap;gap:{position === 'right'
        ? '6px'
        : '14px'};padding:{position === 'right'
        ? '8px 6px'
        : '6px 8px'};align-items:{position === 'right'
        ? 'flex-start'
        : 'center'};justify-content:{position === 'right'
        ? 'flex-start'
        : 'center'};font-family:{theme.typography.fontFamily};font-size:{theme.axis.fontSize}px;color:{theme.axis.textColor};pointer-events:auto;flex-shrink:0;"
    >
      {#each items as item, i (i)}
        <div style="display:flex;align-items:center;gap:4px;user-select:none;">
          <span style="width:8px;height:8px;border-radius:2px;background:{item.color};flex-shrink:0;" />
          <span style="white-space:nowrap;">{item.label}</span>
        </div>
      {/each}
    </div>
  {:else if legendItems.length > 0}
    <div
      use:portal={anchor}
      data-legend={position}
      style="display:flex;flex-direction:{position === 'right'
        ? 'column'
        : 'row'};flex-wrap:wrap;gap:{position === 'right'
        ? '6px'
        : '14px'};padding:{position === 'right'
        ? '8px 6px'
        : '6px 8px'};align-items:{position === 'right'
        ? 'flex-start'
        : 'center'};justify-content:{position === 'right'
        ? 'flex-start'
        : 'center'};font-family:{theme.typography.fontFamily};font-size:{theme.axis.fontSize}px;color:{theme.axis.textColor};pointer-events:auto;flex-shrink:0;"
    >
      {#each legendItems as item (item.id)}
        <button
          type="button"
          on:click={() => handleClick(item)}
          style="display:flex;align-items:center;gap:4px;cursor:pointer;opacity:{item.isDisabled
            ? 0.35
            : 1};transition:opacity 0.15s ease;user-select:none;border:none;background:transparent;padding:0;margin:0;font:inherit;color:inherit;text-align:left;"
        >
          <span style="width:8px;height:8px;border-radius:2px;background:{item.color};flex-shrink:0;" />
          <span style="white-space:nowrap;">{item.label}</span>
        </button>
      {/each}
    </div>
  {/if}
{/if}

// packages/vue/src/ui/Legend.vue
<script setup lang="ts">
import type { ChartInstance, LegendItem } from '@wick-charts/core';
import { computed, inject, onMounted, onUnmounted, ref, useSlots } from 'vue';

import { LegendAnchorKey, LegendRightAnchorKey, ThemeKey, useChartInstance } from '../context';

/**
 * Minimal visual shape the {@link LegendProps.items} override accepts. The
 * canonical {@link LegendItem} (re-exported from `@wick-charts/core`) carries
 * the full identity + closures; those aren't meaningful for a pre-baked,
 * non-interactive legend.
 */
export interface LegendItemOverride {
  label: string;
  color: string;
}

type LegendMode = 'toggle' | 'isolate' | 'solo';

/** Payload for the `onToggle` prop — one entry per user click, regardless of built-in vs custom rendering. */
export interface LegendToggleInfo {
  /** The clicked item's id (matches {@link LegendItem.id}). */
  id: string;
  /** Which interaction produced this change. */
  action: 'toggle' | 'isolate' | 'unisolate';
}

const props = withDefaults(
  defineProps<{
    items?: LegendItemOverride[];
    position?: 'bottom' | 'right';
    /** `'isolate'` shows only the clicked item; `'solo'` is a @deprecated alias. */
    mode?: LegendMode;
    /** Fired after a click changes series visibility — via the built-in UI or a custom slot calling `item.toggle()`/`isolate()` directly. */
    onToggle?: (info: LegendToggleInfo) => void;
  }>(),
  {
    position: 'bottom',
    mode: 'toggle',
  },
);

defineSlots<{
  default?(ctx: { items: readonly LegendItem[] }): unknown;
}>();

const chart = useChartInstance();
const theme = inject(ThemeKey);
const bottomAnchor = inject(LegendAnchorKey);
const rightAnchor = inject(LegendRightAnchorKey);

if (!theme) {
  throw new Error('<Legend> must be used within <ChartContainer>: missing ThemeKey.');
}
if (!bottomAnchor || !rightAnchor) {
  throw new Error('<Legend> must be used within <ChartContainer>: missing legend anchors.');
}

const anchor = computed(() => (props.position === 'right' ? rightAnchor.value : bottomAnchor.value));

const isolatedId = ref<string | null>(null);
const bump = ref(0);

const overlayHandler = () => {
  bump.value++;
};
const seriesChangeHandler = () => {
  isolatedId.value = null;
};

onMounted(() => {
  chart.on('overlayChange', overlayHandler);
  chart.on('seriesChange', seriesChangeHandler);
  if (chart.getSeriesIds().length > 0) bump.value++;
});

onUnmounted(() => {
  chart.off('overlayChange', overlayHandler);
  chart.off('seriesChange', seriesChangeHandler);
});

interface MakeItemArgs {
  id: string;
  seriesId: string;
  layerIndex: number | undefined;
  label: string;
  color: string;
  isDisabled: boolean;
}

function makeItem(args: MakeItemArgs): LegendItem {
  const { id, seriesId, layerIndex, label, color, isDisabled } = args;

  const toggle = () => {
    if (layerIndex !== undefined) {
      chart.setLayerVisible(seriesId, layerIndex, !chart.isLayerVisible(seriesId, layerIndex));
    } else {
      chart.setSeriesVisible(seriesId, !chart.isSeriesVisible(seriesId));
    }
    props.onToggle?.({ id, action: 'toggle' });
  };

  const isolate = () => {
    if (isolatedId.value === id) {
      chart.batch(() => {
        for (const sid of chart.getSeriesIds()) {
          chart.setSeriesVisible(sid, true);
          const layers = chart.getSeriesLayers(sid);
          if (layers) {
            for (let i = 0; i < layers.length; i++) chart.setLayerVisible(sid, i, true);
          }
        }
      });
      isolatedId.value = null;
      props.onToggle?.({ id, action: 'unisolate' });

      return;
    }

    chart.batch(() => {
      for (const sid of chart.getSeriesIds()) {
        const layers = chart.getSeriesLayers(sid);
        if (layers) {
          chart.setSeriesVisible(sid, sid === seriesId);
          for (let i = 0; i < layers.length; i++) {
            chart.setLayerVisible(sid, i, sid === seriesId && i === layerIndex);
          }
        } else {
          chart.setSeriesVisible(sid, sid === id);
        }
      }
    });
    isolatedId.value = id;
    props.onToggle?.({ id, action: 'isolate' });
  };

  return { id, seriesId, layerIndex, label, color, isDisabled, toggle, isolate };
}

function buildLegendItems(c: ChartInstance): LegendItem[] {
  const items: LegendItem[] = [];
  for (const seriesId of c.getSeriesIds()) {
    const layers = c.getSeriesLayers(seriesId);
    if (layers) {
      for (let layerIndex = 0; layerIndex < layers.length; layerIndex++) {
        const id = `${seriesId}_layer${layerIndex}`;
        const visible = c.isSeriesVisible(seriesId) && c.isLayerVisible(seriesId, layerIndex);
        items.push(
          makeItem({
            id,
            seriesId,
            layerIndex,
            label: c.getLayerLabel(seriesId, layerIndex) ?? `Series ${layerIndex + 1}`,
            color: layers[layerIndex].color,
            isDisabled: !visible,
          }),
        );
      }
    } else {
      const color = c.getSeriesColor(seriesId);
      if (!color) continue;

      const label = c.getSeriesLabel(seriesId);
      const visible = c.isSeriesVisible(seriesId);
      items.push(
        makeItem({
          id: seriesId,
          seriesId,
          layerIndex: undefined,
          label: label ?? 'Series',
          color,
          isDisabled: !visible,
        }),
      );
    }
  }

  return items;
}

const legendItems = computed<LegendItem[]>(() => {
  void bump.value;
  void isolatedId.value;

  return buildLegendItems(chart);
});

const slots = useSlots();
const hasCustomSlot = computed(() => typeof slots.default === 'function');

function handleClick(item: LegendItem) {
  if (props.mode === 'isolate' || props.mode === 'solo') item.isolate();
  else item.toggle();
}
</script>

<template>
  <Teleport v-if="anchor && theme" :to="anchor">
    <div
      v-if="hasCustomSlot && legendItems.length > 0"
      :data-legend="position"
      :style="{
        display: 'flex',
        flexDirection: position === 'right' ? 'column' : 'row',
        flexWrap: 'wrap',
        gap: position === 'right' ? '6px' : '14px',
        padding: position === 'right' ? '8px 6px' : '6px 8px',
        alignItems: position === 'right' ? 'flex-start' : 'center',
        justifyContent: position === 'right' ? 'flex-start' : 'center',
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.axis.fontSize + 'px',
        color: theme.axis.textColor,
        pointerEvents: 'auto',
        flexShrink: 0,
      }"
    >
      <slot :items="legendItems" />
    </div>

    <div
      v-else-if="items && items.length > 0"
      :data-legend="position"
      :style="{
        display: 'flex',
        flexDirection: position === 'right' ? 'column' : 'row',
        flexWrap: 'wrap',
        gap: position === 'right' ? '6px' : '14px',
        padding: position === 'right' ? '8px 6px' : '6px 8px',
        alignItems: position === 'right' ? 'flex-start' : 'center',
        justifyContent: position === 'right' ? 'flex-start' : 'center',
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.axis.fontSize + 'px',
        color: theme.axis.textColor,
        pointerEvents: 'auto',
        flexShrink: 0,
      }"
    >
      <div
        v-for="(item, i) in items"
        :key="i"
        :style="{
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
          userSelect: 'none',
        }"
      >
        <span
          :style="{
            width: '8px',
            height: '8px',
            borderRadius: '2px',
            background: item.color,
            flexShrink: 0,
          }"
        />
        <span style="white-space: nowrap">{{ item.label }}</span>
      </div>
    </div>

    <div
      v-else-if="legendItems.length > 0"
      :data-legend="position"
      :style="{
        display: 'flex',
        flexDirection: position === 'right' ? 'column' : 'row',
        flexWrap: 'wrap',
        gap: position === 'right' ? '6px' : '14px',
        padding: position === 'right' ? '8px 6px' : '6px 8px',
        alignItems: position === 'right' ? 'flex-start' : 'center',
        justifyContent: position === 'right' ? 'flex-start' : 'center',
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.axis.fontSize + 'px',
        color: theme.axis.textColor,
        pointerEvents: 'auto',
        flexShrink: 0,
      }"
    >
      <button
        v-for="item in legendItems"
        :key="item.id"
        type="button"
        @click="handleClick(item)"
        :style="{
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
          cursor: 'pointer',
          opacity: item.isDisabled ? 0.35 : 1,
          transition: 'opacity 0.15s ease',
          userSelect: 'none',
          border: 'none',
          background: 'transparent',
          padding: 0,
          margin: 0,
          font: 'inherit',
          color: 'inherit',
          textAlign: 'left',
        }"
      >
        <span
          :style="{
            width: '8px',
            height: '8px',
            borderRadius: '2px',
            background: item.color,
            flexShrink: 0,
          }"
        />
        <span style="white-space: nowrap">{{ item.label }}</span>
      </button>
    </div>
  </Teleport>
</template>
