// packages/svelte/src/ui/ReferenceLine.svelte
<script lang="ts">
import type { ReferenceLineStyle, TimeValue } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from '../context';

/** Horizontal line at this Y data value. Mutually exclusive with `time`. */
export let value: number | undefined = undefined;
/** Vertical line at this `time` (epoch ms or `Date`). Mutually exclusive with `value`. */
export let time: TimeValue | undefined = undefined;
/** Line and label-chip accent color. Default: the theme line color. */
export let color: string | undefined = undefined;
/** Optional text label drawn in an annotation chip at the line's near end. */
export let label: string | undefined = undefined;
/** Dash style. Default: `'dashed'`. */
export let style: ReferenceLineStyle | undefined = undefined;
/** Stroke width in CSS pixels. Default: `1`. */
export let width: number | undefined = undefined;

const chartStore = getChartContext();
let lineId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;

  lineId = chart.addLine({ value, time, color, label, style, width });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (lineId !== null && chart) chart.removeLine(lineId);
  lineId = null;
});

// Push prop changes through to the live line (the first pass runs before
// onMount sets lineId, so it's a guarded no-op).
$: {
  const chart = $chartStore;
  if (lineId !== null && chart) {
    chart.updateLine(lineId, { value, time, color, label, style, width });
  }
}
</script>

// packages/vue/src/ui/ReferenceLine.vue
<script setup lang="ts">
import type { ReferenceLineStyle, TimeValue } from '@wick-charts/core';
import { onMounted, onUnmounted, watch } from 'vue';

import { useChartInstance } from '../context';

const props = defineProps<{
  /** Horizontal line at this Y data value. Mutually exclusive with `time`. */
  value?: number;
  /** Vertical line at this `time` (epoch ms or `Date`). Mutually exclusive with `value`. */
  time?: TimeValue;
  /** Line and label-chip accent color. Default: the theme line color. */
  color?: string;
  /** Optional text label drawn in an annotation chip at the line's near end. */
  label?: string;
  /** Dash style. Default: `'dashed'`. */
  style?: ReferenceLineStyle;
  /** Stroke width in CSS pixels. Default: `1`. */
  width?: number;
}>();

const chart = useChartInstance();
let lineId: string | null = null;

onMounted(() => {
  lineId = chart.addLine({
    value: props.value,
    time: props.time,
    color: props.color,
    label: props.label,
    style: props.style,
    width: props.width,
  });
});

onUnmounted(() => {
  if (lineId !== null) chart.removeLine(lineId);
  lineId = null;
});

watch(
  () => [props.value, props.time, props.color, props.label, props.style, props.width],
  () => {
    if (lineId === null) return;

    chart.updateLine(lineId, {
      value: props.value,
      time: props.time,
      color: props.color,
      label: props.label,
      style: props.style,
      width: props.width,
    });
  },
);
</script>

<template><span v-if="false" /></template>
