// packages/react/src/ui/TimeAxis.tsx
import { useRef } from 'react';

import { formatTime } from '@wick-charts/core';
import { useChartInstance } from '../context';
import { useVisibleRange } from '../store-bridge';

interface TrackedTick {
  opacity: number;
  addedAt: number;
}

export function TimeAxis() {
  const chart = useChartInstance();
  const visibleRange = useVisibleRange(chart);
  const theme = chart.getTheme();
  const dataInterval = chart.getDataInterval();
  const { ticks: currentTicks, tickInterval } = chart.timeScale.niceTickValues(dataInterval);
  const currentSet = new Set(currentTicks);

  // Persistent map: tick value → tracked state
  const mapRef = useRef<Map<number, TrackedTick>>(new Map());
  const map = mapRef.current;
  const now = performance.now();

  // Mark current ticks as visible
  for (const t of currentTicks) {
    if (!map.has(t)) {
      map.set(t, { opacity: 1, addedAt: now });
    } else {
      map.get(t)!.opacity = 1;
    }
  }

  // Mark missing ticks for fade-out
  for (const [t, entry] of map) {
    if (!currentSet.has(t)) {
      entry.opacity = 0;
    }
  }

  // Clean up old faded-out ticks (keep for 400ms for CSS transition)
  for (const [t, entry] of map) {
    if (entry.opacity === 0 && now - entry.addedAt > 5000) {
      map.delete(t);
    }
  }

  // Collect all ticks to render (current + fading out)
  const allTicks = Array.from(map.entries());

  return (
    <div
      style={{
        position: 'absolute',
        left: 0,
        bottom: 0,
        right: chart.yAxisWidth,
        height: chart.xAxisHeight,
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
      }}
    >
      {allTicks.map(([time, entry]) => {
        const x = chart.timeScale.timeToX(time);
        return (
          <span
            key={time}
            style={{
              position: 'absolute',
              left: x,
              transform: 'translateX(-50%)',
              color: theme.axis.textColor,
              fontSize: theme.typography.axisFontSize,
              fontFamily: theme.typography.fontFamily,
              userSelect: 'none',
              whiteSpace: 'nowrap',
              opacity: entry.opacity,
              transition: 'opacity 0.3s ease',
              willChange: 'opacity',
            }}
          >
            {formatTime(time, tickInterval)}
          </span>
        );
      })}
    </div>
  );
}

// packages/vue/src/ui/TimeAxis.vue
<script setup lang="ts">
import { formatTime } from '@wick-charts/core';
import { computed } from 'vue';

import { useVisibleRange } from '../composables';
import { useChartInstance } from '../context';

interface TrackedTick {
  opacity: number;
  addedAt: number;
}

const chart = useChartInstance();
const _visibleRange = useVisibleRange(chart);

const tickMap = new Map<number, TrackedTick>();

const theme = computed(() => chart.getTheme());

const tickData = computed(() => {
  // Access _visibleRange.value to track dependency
  void _visibleRange.value;

  const dataInterval = chart.getDataInterval();
  const { ticks: currentTicks, tickInterval } = chart.timeScale.niceTickValues(dataInterval);
  const currentSet = new Set(currentTicks);
  const now = performance.now();

  // Mark current ticks as visible
  for (const t of currentTicks) {
    if (!tickMap.has(t)) {
      tickMap.set(t, { opacity: 1, addedAt: now });
    } else {
      tickMap.get(t)!.opacity = 1;
    }
  }

  // Mark missing ticks for fade-out
  for (const [t, entry] of tickMap) {
    if (!currentSet.has(t)) {
      entry.opacity = 0;
    }
  }

  // Clean up old faded-out ticks
  for (const [t, entry] of tickMap) {
    if (entry.opacity === 0 && now - entry.addedAt > 5000) {
      tickMap.delete(t);
    }
  }

  return {
    allTicks: Array.from(tickMap.entries()),
    tickInterval,
  };
});
</script>

<template>
  <div
    :style="{
      position: 'absolute',
      left: '0',
      bottom: '0',
      right: chart.yAxisWidth + 'px',
      height: chart.xAxisHeight + 'px',
      pointerEvents: 'none',
      display: 'flex',
      alignItems: 'center',
    }"
  >
    <span
      v-for="[time, entry] in tickData.allTicks"
      :key="time"
      :style="{
        position: 'absolute',
        left: chart.timeScale.timeToX(time) + 'px',
        transform: 'translateX(-50%)',
        color: theme.axis.textColor,
        fontSize: theme.typography.axisFontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        userSelect: 'none',
        whiteSpace: 'nowrap',
        opacity: entry.opacity,
        transition: 'opacity 0.3s ease',
        willChange: 'opacity',
      }"
    >
      {{ formatTime(time, tickData.tickInterval) }}
    </span>
  </div>
</template>
