// packages/svelte/src/ui/Title.svelte
<script lang="ts">
import { getThemeContext, getTitleAnchor } from '../context';
import { portal } from './portal';

export let sub: string | undefined = undefined;

const themeStore = getThemeContext();
const anchorStore = getTitleAnchor();

$: theme = $themeStore;
$: anchor = $anchorStore;
</script>

{#if anchor}
  <div
    use:portal={anchor}
    data-chart-title=""
    style="
      display:flex;
      align-items:baseline;
      gap:6px;
      padding:6px 8px 4px;
      flex-shrink:0;
      font-family:{theme.typography.fontFamily};
      font-size:{theme.typography.fontSize}px;
      font-weight:600;
      color:{theme.tooltip.textColor};
      pointer-events:none;
    "
  >
    <span><slot /></span>
    {#if sub}
      <span
        style="
          font-weight:400;
          color:{theme.axis.textColor};
          font-size:{theme.typography.axisFontSize}px;
        "
      >{sub}</span>
    {/if}
  </div>
{/if}

// packages/vue/src/ui/Title.vue
<script setup lang="ts">
import { inject } from 'vue';

import { ThemeKey, TitleAnchorKey } from '../context';

withDefaults(
  defineProps<{
    sub?: string;
  }>(),
  {},
);

const anchor = inject(TitleAnchorKey);
const theme = inject(ThemeKey);

// Match the "loud failure" contract of other Vue overlays (`useChartInstance`,
// `useTheme`) — misuse outside `<ChartContainer>` should throw, not render
// nothing silently.
if (!anchor) {
  throw new Error('<Title> must be used within <ChartContainer>: missing TitleAnchorKey.');
}
if (!theme) {
  throw new Error('<Title> must be used within <ChartContainer>: missing ThemeKey.');
}
</script>

<template>
  <Teleport v-if="anchor" :to="anchor">
    <div
      data-chart-title=""
      :style="{
        display: 'flex',
        alignItems: 'baseline',
        gap: '6px',
        padding: '6px 8px 4px',
        flexShrink: 0,
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.typography.fontSize + 'px',
        fontWeight: 600,
        color: theme.tooltip.textColor,
        pointerEvents: 'none',
      }"
    >
      <span><slot /></span>
      <span
        v-if="sub"
        :style="{
          fontWeight: 400,
          color: theme.axis.textColor,
          fontSize: theme.typography.axisFontSize + 'px',
        }"
      >
        {{ sub }}
      </span>
    </div>
  </Teleport>
</template>
