// src/ui/Tooltip.tsx
import { useMemo } from "react";
import type { LineData, OHLCData } from "../core/types";
import { useChartInstance } from "../react/context";
import { useCrosshairPosition, useLastPrice } from "../react/store-bridge";
import { formatDate, formatTime } from "../utils/time";

export interface TooltipProps {
  seriesId: string;
}

/**
 * Two-part tooltip:
 * 1. Compact legend always visible in top-left
 * 2. Floating glass tooltip near cursor on hover
 */
export function Tooltip({ seriesId }: TooltipProps) {
  const chart = useChartInstance();
  const crosshair = useCrosshairPosition(chart);
  const lastPrice = useLastPrice(chart, seriesId);

  const hoverData = useMemo(() => {
    if (!crosshair) return null;
    return chart.getDataAtTime(seriesId, crosshair.time);
  }, [chart, seriesId, crosshair?.time]);

  const lastData = useMemo(() => {
    return chart.getLastData(seriesId);
  }, [chart, seriesId, lastPrice]);

  const displayData = hoverData ?? lastData;
  if (!displayData) return null;

  const theme = chart.getTheme();
  const isOHLC = "open" in displayData;
  const ohlc = displayData as OHLCData;
  const line = displayData as LineData;
  const isUp = isOHLC ? ohlc.close >= ohlc.open : true;
  const dataInterval = chart.getDataInterval();
  const mediaSize = chart.getMediaSize();

  const upColor = theme.candlestick.upColor;
  const downColor = theme.candlestick.downColor;
  const valueColor = isOHLC ? (isUp ? upColor : downColor) : theme.line.color;
  const labelColor = theme.axis.textColor;

  return (
    <>
      {/* ── Compact legend (below chart title) ── */}
      <div
        style={{
          position: "absolute",
          top: 24,
          left: 8,
          pointerEvents: "none",
          display: "flex",
          alignItems: "center",
          gap: 4,
          fontSize: theme.typography.fontSize,
          fontFamily: theme.typography.fontFamily,
          fontVariantNumeric: "tabular-nums",
          opacity: crosshair ? 1 : 0.6,
          transition: "opacity 0.2s ease",
        }}
      >
        <span style={{ color: labelColor, marginRight: 2 }}>{formatTime(displayData.time, dataInterval)}</span>
        {isOHLC ? (
          <>
            <LegendItem label="O" value={ohlc.open} color={valueColor} dim={labelColor} />
            <LegendItem label="H" value={ohlc.high} color={valueColor} dim={labelColor} />
            <LegendItem label="L" value={ohlc.low} color={valueColor} dim={labelColor} />
            <LegendItem label="C" value={ohlc.close} color={valueColor} dim={labelColor} />
            {ohlc.volume != null && (
              <LegendItem label="V" value={ohlc.volume} color={labelColor} dim={labelColor} volume />
            )}
          </>
        ) : (
          <span style={{ color: valueColor, fontWeight: 500 }}>{line.value.toFixed(2)}</span>
        )}
      </div>

      {/* ── Floating tooltip (near cursor, only on hover) ── */}
      {crosshair && hoverData && (
        <FloatingTooltip
          data={hoverData}
          x={crosshair.mediaX}
          y={crosshair.mediaY}
          chartWidth={mediaSize.width - 70}
          chartHeight={mediaSize.height - 30}
          theme={theme}
          dataInterval={dataInterval}
        />
      )}
    </>
  );
}

function LegendItem({
  label,
  value,
  color,
  dim,
  volume,
}: {
  label: string;
  value: number;
  color: string;
  dim: string;
  volume?: boolean;
}) {
  return (
    <>
      <span style={{ color: dim, opacity: 0.5, marginLeft: 5 }}>{label}</span>
      <span style={{ color, fontWeight: 500, marginLeft: 2 }}>{volume ? formatVolume(value) : value.toFixed(2)}</span>
    </>
  );
}

function FloatingTooltip({
  data,
  x,
  y,
  chartWidth,
  chartHeight,
  theme,
  dataInterval,
}: {
  data: OHLCData | LineData;
  x: number;
  y: number;
  chartWidth: number;
  chartHeight: number;
  theme: any;
  dataInterval: number;
}) {
  const isOHLC = "open" in data;
  const ohlc = data as OHLCData;
  const line = data as LineData;
  const isUp = isOHLC ? ohlc.close >= ohlc.open : true;

  const upColor = theme.candlestick.upColor;
  const downColor = theme.candlestick.downColor;

  // Position: offset from cursor, flip near edges
  const tooltipWidth = 160;
  const tooltipHeight = isOHLC ? 140 : 60;
  const offsetX = 16;
  const offsetY = 16;

  const left = x + offsetX + tooltipWidth > chartWidth ? x - offsetX - tooltipWidth : x + offsetX;
  const top = y + offsetY + tooltipHeight > chartHeight ? y - offsetY - tooltipHeight : y + offsetY;

  const bg = theme.tooltip.background;
  const border = theme.tooltip.borderColor;
  const shadow = "0 8px 32px rgba(0,0,0,0.4), 0 2px 8px rgba(0,0,0,0.2)";

  return (
    <div
      style={{
        position: "absolute",
        left,
        top,
        pointerEvents: "none",
        background: bg,
        backdropFilter: "blur(12px)",
        WebkitBackdropFilter: "blur(12px)",
        border: `1px solid ${border}`,
        borderRadius: 8,
        padding: "10px 14px",
        boxShadow: shadow,
        fontSize: theme.typography.fontSize,
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: "tabular-nums",
        color: theme.tooltip.textColor,
        minWidth: 140,
        zIndex: 10,
        transition: "opacity 0.15s ease",
      }}
    >
      {/* Time header */}
      <div
        style={{
          fontSize: theme.typography.axisFontSize,
          color: theme.axis.textColor,
          marginBottom: 8,
          paddingBottom: 6,
          borderBottom: `1px solid ${border}`,
          letterSpacing: "0.02em",
        }}
      >
        {formatDate(data.time)} {formatTime(data.time, dataInterval)}
      </div>

      {isOHLC ? (
        <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "4px 12px" }}>
          <TooltipRow label="Open" value={ohlc.open} color={isUp ? upColor : downColor} />
          <TooltipRow label="High" value={ohlc.high} color={isUp ? upColor : downColor} />
          <TooltipRow label="Low" value={ohlc.low} color={isUp ? upColor : downColor} />
          <TooltipRow label="Close" value={ohlc.close} color={isUp ? upColor : downColor} />
          {ohlc.volume != null && (
            <TooltipRow label="Volume" value={ohlc.volume} color={theme.tooltip.textColor} volume />
          )}
        </div>
      ) : (
        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <span style={{ opacity: 0.6 }}>Value</span>
          <span style={{ fontWeight: 600, color: theme.line.color }}>{line.value.toFixed(2)}</span>
        </div>
      )}
    </div>
  );
}

function TooltipRow({
  label,
  value,
  color,
  volume,
}: {
  label: string;
  value: number;
  color: string;
  volume?: boolean;
}) {
  return (
    <>
      <span style={{ opacity: 0.5 }}>{label}</span>
      <span style={{ fontWeight: 600, color, textAlign: "right" }}>
        {volume ? formatVolume(value) : value.toFixed(2)}
      </span>
    </>
  );
}

function formatVolume(v: number): string {
  if (v >= 1e9) return (v / 1e9).toFixed(2) + "B";
  if (v >= 1e6) return (v / 1e6).toFixed(2) + "M";
  if (v >= 1e3) return (v / 1e3).toFixed(1) + "K";
  return v.toFixed(0);
}

// packages/vue/src/ui/Tooltip.vue
<script setup lang="ts">
import { computed } from 'vue';
import { formatDate, formatTime, type LineData, type OHLCData } from '@wick-charts/core';
import { useChartInstance } from '../context';
import { useCrosshairPosition, useLastPrice } from '../composables';

type TooltipSort = 'none' | 'asc' | 'desc';

interface SeriesSnapshot {
  id: string;
  label?: string;
  data: OHLCData | LineData;
  color: string;
}

const props = withDefaults(defineProps<{
  seriesId?: string;
  sort?: TooltipSort;
}>(), {
  sort: 'none',
});

const chart = useChartInstance();
const crosshair = useCrosshairPosition(chart);

const targetIds = computed(() => {
  if (props.seriesId) return [props.seriesId];
  return chart.getSeriesIds();
});

const primaryId = computed(() => targetIds.value[0] ?? '');
const lastPrice = useLastPrice(chart, primaryId.value);

const theme = computed(() => chart.getTheme());
const dataInterval = computed(() => chart.getDataInterval());

function sortSnapshots(snapshots: SeriesSnapshot[], sort: TooltipSort): SeriesSnapshot[] {
  if (sort === 'none' || snapshots.length <= 1) return snapshots;
  return [...snapshots].sort((a, b) => {
    const av = 'value' in a.data ? (a.data as LineData).value : (a.data as OHLCData).close;
    const bv = 'value' in b.data ? (b.data as LineData).value : (b.data as OHLCData).close;
    return sort === 'asc' ? av - bv : bv - av;
  });
}

function formatVolume(v: number): string {
  if (v >= 1e9) return (v / 1e9).toFixed(2) + 'B';
  if (v >= 1e6) return (v / 1e6).toFixed(2) + 'M';
  if (v >= 1e3) return (v / 1e3).toFixed(1) + 'K';
  return v.toFixed(0);
}

const snapshots = computed(() => {
  // Access reactive dependencies
  void lastPrice.value;

  const hoverSnapshots: SeriesSnapshot[] = [];
  if (crosshair.value) {
    for (const id of targetIds.value) {
      const d = chart.getDataAtTime(id, crosshair.value.time);
      if (d) {
        hoverSnapshots.push({
          id,
          label: chart.getSeriesLabel(id),
          data: d,
          color: chart.getSeriesColor(id) ?? '#888',
        });
      }
    }
  }

  const lastSnapshots: SeriesSnapshot[] = [];
  for (const id of targetIds.value) {
    const d = chart.getLastData(id);
    if (d) {
      lastSnapshots.push({
        id,
        label: chart.getSeriesLabel(id),
        data: d,
        color: chart.getSeriesColor(id) ?? '#888',
      });
    }
  }

  const raw = hoverSnapshots.length > 0 ? hoverSnapshots : lastSnapshots;
  return sortSnapshots(raw, props.sort);
});

const hoverSnapshots = computed(() => {
  if (!crosshair.value) return [];
  const result: SeriesSnapshot[] = [];
  for (const id of targetIds.value) {
    const d = chart.getDataAtTime(id, crosshair.value.time);
    if (d) {
      result.push({
        id,
        label: chart.getSeriesLabel(id),
        data: d,
        color: chart.getSeriesColor(id) ?? '#888',
      });
    }
  }
  return sortSnapshots(result, props.sort);
});

const displayTime = computed(() => {
  if (snapshots.value.length === 0) return 0;
  return snapshots.value[0].data.time;
});

const floatingPos = computed(() => {
  if (!crosshair.value || hoverSnapshots.value.length === 0) return null;
  const mediaSize = chart.getMediaSize();
  const hasOHLC = hoverSnapshots.value.some((s) => 'open' in s.data);
  const lineCount = hoverSnapshots.value.filter((s) => !('open' in s.data)).length;

  const tooltipWidth = 160;
  const tooltipHeight = hasOHLC ? 140 : 40 + lineCount * 22;
  const offsetX = 16;
  const offsetY = 16;
  const chartWidth = mediaSize.width - chart.yAxisWidth;
  const chartHeight = mediaSize.height - chart.xAxisHeight;

  const left =
    crosshair.value.mediaX + offsetX + tooltipWidth > chartWidth
      ? crosshair.value.mediaX - offsetX - tooltipWidth
      : crosshair.value.mediaX + offsetX;
  const top =
    crosshair.value.mediaY + offsetY + tooltipHeight > chartHeight
      ? crosshair.value.mediaY - offsetY - tooltipHeight
      : crosshair.value.mediaY + offsetY;

  return { left, top };
});

function isOHLC(data: OHLCData | LineData): data is OHLCData {
  return 'open' in data;
}
</script>

<template>
  <template v-if="snapshots.length > 0">
    <!-- Compact legend (top-left, always visible) -->
    <div
      :style="{
        position: 'absolute',
        top: '24px',
        left: '8px',
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        flexWrap: 'wrap',
        maxWidth: '70%',
        fontSize: theme.typography.fontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        opacity: crosshair ? 1 : 0.6,
        transition: 'opacity 0.2s ease',
      }"
    >
      <span :style="{ color: theme.axis.textColor, marginRight: '2px' }">
        {{ formatTime(displayTime, dataInterval) }}
      </span>
      <template v-for="s in snapshots" :key="s.id">
        <!-- OHLC legend -->
        <span v-if="isOHLC(s.data)" :style="{ display: 'inline-flex', alignItems: 'center', gap: '4px' }">
          <template v-for="field in (['O', 'H', 'L', 'C'] as const)" :key="field">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">{{ field }}</span>
            <span
              :style="{
                color: (s.data as OHLCData).close >= (s.data as OHLCData).open ? theme.candlestick.upColor : theme.candlestick.downColor,
                fontWeight: 500,
                marginLeft: '2px',
              }"
            >
              {{ ({ O: (s.data as OHLCData).open, H: (s.data as OHLCData).high, L: (s.data as OHLCData).low, C: (s.data as OHLCData).close })[field].toFixed(2) }}
            </span>
          </template>
          <template v-if="(s.data as OHLCData).volume != null">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">V</span>
            <span :style="{ color: theme.axis.textColor, fontWeight: 500, marginLeft: '2px' }">
              {{ formatVolume((s.data as OHLCData).volume!) }}
            </span>
          </template>
        </span>
        <!-- Line legend -->
        <span v-else :style="{ display: 'inline-flex', alignItems: 'center', gap: '3px' }">
          <span
            :style="{
              width: '6px',
              height: '6px',
              borderRadius: '50%',
              background: s.color,
              flexShrink: 0,
            }"
          />
          <span :style="{ color: s.color, fontWeight: 500 }">
            {{ (s.data as LineData).value.toFixed(2) }}
          </span>
        </span>
      </template>
    </div>

    <!-- Floating tooltip (near cursor, only on hover) -->
    <div
      v-if="crosshair && hoverSnapshots.length > 0 && floatingPos"
      :style="{
        position: 'absolute',
        left: floatingPos.left + 'px',
        top: floatingPos.top + 'px',
        pointerEvents: 'none',
        background: theme.tooltip.background,
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        border: '1px solid ' + theme.tooltip.borderColor,
        borderRadius: '8px',
        padding: '10px 14px',
        boxShadow: '0 4px 16px rgba(0,0,0,0.1), 0 1px 4px rgba(0,0,0,0.06)',
        fontSize: theme.typography.tooltipFontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        color: theme.tooltip.textColor,
        minWidth: '140px',
        zIndex: 10,
        transition: 'opacity 0.15s ease',
      }"
    >
      <!-- Time header -->
      <div
        :style="{
          fontSize: theme.typography.axisFontSize + 'px',
          color: theme.axis.textColor,
          marginBottom: '8px',
          paddingBottom: '6px',
          borderBottom: '1px solid ' + theme.tooltip.borderColor,
          letterSpacing: '0.02em',
        }"
      >
        {{ formatDate(displayTime) }} {{ formatTime(displayTime, dataInterval) }}
      </div>

      <template v-for="s in snapshots" :key="s.id">
        <!-- OHLC floating -->
        <div
          v-if="isOHLC(s.data)"
          :style="{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '4px 12px' }"
        >
          <template v-for="row in [
            { label: 'Open', val: (s.data as OHLCData).open },
            { label: 'High', val: (s.data as OHLCData).high },
            { label: 'Low', val: (s.data as OHLCData).low },
            { label: 'Close', val: (s.data as OHLCData).close },
          ]" :key="row.label">
            <span :style="{ opacity: 0.5 }">{{ row.label }}</span>
            <span
              :style="{
                fontWeight: 600,
                color: (s.data as OHLCData).close >= (s.data as OHLCData).open
                  ? theme.candlestick.upColor
                  : theme.candlestick.downColor,
                textAlign: 'right',
              }"
            >{{ row.val.toFixed(2) }}</span>
          </template>
          <template v-if="(s.data as OHLCData).volume != null">
            <span :style="{ opacity: 0.5 }">Volume</span>
            <span :style="{ fontWeight: 600, color: theme.tooltip.textColor, textAlign: 'right' }">
              {{ formatVolume((s.data as OHLCData).volume!) }}
            </span>
          </template>
        </div>
        <!-- Line floating -->
        <div
          v-else
          :style="{ display: 'flex', alignItems: 'center', gap: '8px', padding: '2px 0' }"
        >
          <span
            :style="{
              width: '8px',
              height: '8px',
              borderRadius: '50%',
              background: s.color,
              flexShrink: 0,
            }"
          />
          <span :style="{ opacity: 0.6, flex: '1' }">{{ s.label ?? 'Value' }}</span>
          <span :style="{ fontWeight: 600, color: s.color }">
            {{ (s.data as LineData).value.toFixed(2) }}
          </span>
        </div>
      </template>
    </div>
  </template>
</template>
