// packages/react/src/ui/YLabel.tsx
import { useEffect } from 'react';

import { useChartInstance } from '../context';
import { useLastYValue, usePreviousClose } from '../store-bridge';
import { NumberFlow } from './NumberFlow';

export interface YLabelProps {
  seriesId: string;
  /** Override badge color (e.g. line color). If not set, uses up/down/neutral from theme. */
  color?: string;
}

export function YLabel({ seriesId, color }: YLabelProps) {
  const chart = useChartInstance();

  // Notify chart that YLabel is present (affects right padding)
  useEffect(() => {
    chart.setYLabel(true);
    return () => chart.setYLabel(false);
  }, [chart]);
  const last = useLastYValue(chart, seriesId);
  const previousClose = usePreviousClose(chart, seriesId);

  if (!last) return null;

  const { value, isLive } = last;
  const theme = chart.getTheme();
  const y = chart.yScale.valueToY(value);

  let bgColor: string;
  if (!isLive) {
    bgColor = theme.axis.textColor;
  } else if (color) {
    bgColor = color;
  } else {
    const direction =
      previousClose === null
        ? 'neutral'
        : value > previousClose
          ? 'up'
          : value < previousClose
            ? 'down'
            : 'neutral';
    bgColor =
      direction === 'up'
        ? theme.yLabel.upBackground
        : direction === 'down'
          ? theme.yLabel.downBackground
          : theme.yLabel.neutralBackground;
  }

  const yRange = chart.yScale.getRange();
  const range = yRange.max - yRange.min;
  const fractionDigits = range < 0.1 ? 6 : range < 10 ? 4 : range < 1000 ? 2 : 0;

  return (
    <>
      {/* Horizontal dashed line */}
      <div
        style={{
          position: 'absolute',
          left: 0,
          right: chart.yAxisWidth,
          top: y,
          height: 0,
          borderTop: `1px dashed ${bgColor}`,
          opacity: 0.5,
          pointerEvents: 'none',
          zIndex: 2,
        }}
      />
      {/* Value badge */}
      <div
        style={{
          position: 'absolute',
          right: 4,
          top: y,
          transform: 'translateY(-50%)',
          pointerEvents: 'auto',
          zIndex: 3,
          background: bgColor,
          color: theme.yLabel.textColor,
          fontSize: theme.typography.yFontSize,
          fontFamily: theme.typography.fontFamily,
          padding: '3px 8px',
          borderRadius: 3,
          whiteSpace: 'nowrap',
          transition: 'background-color 0.3s ease',
        }}
      >
        <NumberFlow
          value={value}
          format={{ minimumFractionDigits: fractionDigits, maximumFractionDigits: fractionDigits, useGrouping: false }}
          spinDuration={350}
        />
      </div>
    </>
  );
}

// packages/vue/src/ui/YLabel.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue';

import { useLastYValue, usePreviousClose } from '../composables';
import { useChartInstance } from '../context';
import NumberFlow from './NumberFlow.vue';

const props = defineProps<{
  seriesId: string;
  color?: string;
}>();

const chart = useChartInstance();
const lastY = useLastYValue(chart, props.seriesId);
const previousClose = usePreviousClose(chart, props.seriesId);

onMounted(() => chart.setYLabel(true));
onUnmounted(() => chart.setYLabel(false));

const theme = computed(() => chart.getTheme());

const y = computed(() => {
  if (lastY.value === null) return 0;
  return chart.yScale.valueToY(lastY.value.value);
});

const bgColor = computed(() => {
  if (props.color) return props.color;
  const t = theme.value;
  if (previousClose.value === null || lastY.value === null) {
    return t.yLabel.neutralBackground;
  }
  if (lastY.value.value > previousClose.value) return t.yLabel.upBackground;
  if (lastY.value.value < previousClose.value) return t.yLabel.downBackground;
  return t.yLabel.neutralBackground;
});

const fractionDigits = computed(() => {
  const yRange = chart.yScale.getRange();
  const range = yRange.max - yRange.min;
  if (range < 0.1) return 6;
  if (range < 10) return 4;
  if (range < 1000) return 2;
  return 0;
});

const numberFormat = computed(() => ({
  minimumFractionDigits: fractionDigits.value,
  maximumFractionDigits: fractionDigits.value,
  useGrouping: false,
}));
</script>

<template>
  <template v-if="lastY !== null">
    <!-- Horizontal dashed line -->
    <div
      :style="{
        position: 'absolute',
        left: '0',
        right: chart.yAxisWidth + 'px',
        top: y + 'px',
        height: '0',
        borderTop: '1px dashed ' + bgColor,
        opacity: 0.5,
        pointerEvents: 'none',
        zIndex: 2,
      }"
    />
    <!-- Value badge -->
    <div
      :style="{
        position: 'absolute',
        right: '4px',
        top: y + 'px',
        transform: 'translateY(-50%)',
        pointerEvents: 'auto',
        zIndex: 3,
        background: bgColor,
        color: theme.yLabel.textColor,
        fontSize: theme.typography.yFontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        padding: '3px 8px',
        borderRadius: '3px',
        whiteSpace: 'nowrap',
        transition: 'background-color 0.3s ease',
      }"
    >
      <NumberFlow
        :value="lastY.value"
        :format="numberFormat"
        :spin-duration="350"
      />
    </div>
  </template>
</template>
