// packages/vue/src/ui/HeatmapTooltip.vue
<script setup lang="ts">
import {
  HEATMAP_TOOLTIP_HEIGHT,
  HEATMAP_TOOLTIP_WIDTH,
  type HoverInfo,
  type ValueFormatter,
  computeTooltipPosition,
  defaultHeatmapFormat,
  resolveHeatmapSeriesId,
} from '@wick-charts/core';
import { computed, onMounted, onUnmounted, ref } from 'vue';

import { useCrosshairPosition } from '../composables';
import { useChartInstance } from '../context';

const props = defineProps<{
  /**
   * Owning series id. **Optional** — when omitted, the first visible heatmap
   * series is picked.
   */
  seriesId?: string;
  /** Custom formatter for the cell value. Default: plain integers, compact decimals. */
  format?: ValueFormatter;
}>();

const effectiveFormat = computed<ValueFormatter>(() => props.format ?? defaultHeatmapFormat);

const chart = useChartInstance();
const crosshair = useCrosshairPosition(chart);

const bump = ref(0);
const handler = () => {
  bump.value++;
};
onMounted(() => {
  chart.on('overlayChange', handler);
});
onUnmounted(() => {
  chart.off('overlayChange', handler);
});

const theme = computed(() => {
  // `setTheme` fires `overlayChange`; read `bump` so this computed picks up
  // runtime theme swaps instead of freezing on the first-render snapshot.
  void bump.value;

  return chart.getTheme();
});
const resolvedId = computed<string | null>(() => {
  void bump.value;

  return resolveHeatmapSeriesId(chart, props.seriesId);
});

const info = computed<HoverInfo | null>(() => {
  void crosshair.value;
  void bump.value;
  if (resolvedId.value === null) return null;

  return chart.getHoverInfo(resolvedId.value);
});

const meterWidth = computed(() => {
  if (!info.value) return 0;

  return Math.max(2, Math.min(100, info.value.percent));
});

const tooltipPos = computed(() => {
  if (!crosshair.value || !info.value) return null;
  const mediaSize = chart.getMediaSize();

  return computeTooltipPosition({
    x: crosshair.value.mediaX,
    y: crosshair.value.mediaY,
    chartWidth: mediaSize.width,
    chartHeight: mediaSize.height,
    tooltipWidth: HEATMAP_TOOLTIP_WIDTH,
    tooltipHeight: HEATMAP_TOOLTIP_HEIGHT,
    offsetX: 16,
    offsetY: 16,
  });
});
</script>

<template>
  <div
    v-if="info && crosshair && tooltipPos"
    :style="{
      position: 'absolute',
      left: tooltipPos.left + 'px',
      top: tooltipPos.top + 'px',
      pointerEvents: 'none',
      background: theme.tooltip.background,
      backdropFilter: 'blur(12px)',
      WebkitBackdropFilter: 'blur(12px)',
      border: '1px solid ' + theme.tooltip.borderColor,
      borderRadius: '8px',
      padding: '10px 14px',
      boxShadow: '0 4px 16px rgba(0,0,0,0.1), 0 1px 4px rgba(0,0,0,0.06)',
      fontSize: theme.typography.fontSize + 'px',
      fontFamily: theme.typography.fontFamily,
      color: theme.tooltip.textColor,
      zIndex: 10,
      display: 'flex',
      flexDirection: 'column',
      gap: '6px',
      minWidth: '120px',
    }"
  >
    <div :style="{ display: 'flex', alignItems: 'center', gap: '8px' }">
      <span
        :style="{
          width: '10px',
          height: '10px',
          borderRadius: '3px',
          background: info.color,
          flexShrink: 0,
        }"
      />
      <span :style="{ fontWeight: 600 }">{{ info.label }}</span>
      <span :style="{ marginLeft: 'auto', fontWeight: 600 }">{{ effectiveFormat(info.value) }}</span>
    </div>
    <div
      :style="{
        position: 'relative',
        height: '4px',
        borderRadius: '2px',
        background: theme.tooltip.borderColor,
        overflow: 'hidden',
      }"
    >
      <div
        :style="{
          position: 'absolute',
          inset: '0',
          width: meterWidth + '%',
          borderRadius: '2px',
          background: info.color,
        }"
      />
    </div>
  </div>
</template>

// packages/svelte/src/ui/HeatmapTooltip.svelte
<script lang="ts">
import type { CrosshairPosition, HoverInfo, ValueFormatter } from '@wick-charts/core';
import {
  HEATMAP_TOOLTIP_HEIGHT,
  HEATMAP_TOOLTIP_WIDTH,
  computeTooltipPosition,
  defaultHeatmapFormat,
  resolveHeatmapSeriesId,
} from '@wick-charts/core';
import { onDestroy } from 'svelte';

import { getChartContext } from '../context';
import { createCrosshairPosition } from '../stores';

/**
 * Owning series id. **Optional** — when omitted, the first visible heatmap
 * series is picked.
 */
export let seriesId: string | undefined = undefined;
/** Custom formatter for the cell value. Default: plain integers, compact decimals. */
export let format: ValueFormatter = defaultHeatmapFormat;

const chartStore = getChartContext();
let crosshair: CrosshairPosition | null = null;
let crosshairUnsub: (() => void) | null = null;

let bump = 0;
let overlayUnsub: (() => void) | null = null;

$: {
  const c = $chartStore;
  if (c && !crosshairUnsub) {
    const posStore = createCrosshairPosition(c);
    crosshairUnsub = posStore.subscribe((v) => {
      crosshair = v;
    });
  }
  if (c && !overlayUnsub) {
    const handler = () => {
      bump++;
    };
    c.on('overlayChange', handler);
    overlayUnsub = () => c.off('overlayChange', handler);
  }
}

onDestroy(() => {
  crosshairUnsub?.();
  overlayUnsub?.();
});

$: chart = $chartStore;
// `setTheme` fires `overlayChange`; reading `bump` keeps `theme` live across
// runtime theme swaps instead of freezing on the first-render snapshot.
$: theme = chart && bump >= 0 ? chart.getTheme() : null;
$: resolvedId = chart && bump >= 0 ? resolveHeatmapSeriesId(chart, seriesId) : null;

// Hover-index changes don't emit `overlayChange` — depend on `crosshair` so
// the info re-reads as the pointer moves between cells (mirrors the Vue
// tooltip's `void crosshair.value`).
let info: HoverInfo | null = null;
$: {
  void crosshair;
  info = chart && resolvedId !== null && bump >= 0 ? chart.getHoverInfo(resolvedId) : null;
}
$: mediaSize = chart?.getMediaSize();
$: meterWidth = info ? Math.max(2, Math.min(100, info.percent)) : 0;

$: tooltipPos =
  crosshair && mediaSize
    ? computeTooltipPosition({
        x: crosshair.mediaX,
        y: crosshair.mediaY,
        chartWidth: mediaSize.width,
        chartHeight: mediaSize.height,
        tooltipWidth: HEATMAP_TOOLTIP_WIDTH,
        tooltipHeight: HEATMAP_TOOLTIP_HEIGHT,
        offsetX: 16,
        offsetY: 16,
      })
    : { left: 0, top: 0 };
</script>

{#if info && crosshair && theme && mediaSize}
  <div
    style="position:absolute;left:{tooltipPos.left}px;top:{tooltipPos.top}px;pointer-events:none;background:{theme
      .tooltip
      .background};backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid {theme.tooltip
      .borderColor};border-radius:8px;padding:10px 14px;box-shadow:0 4px 16px rgba(0,0,0,0.1), 0 1px 4px rgba(0,0,0,0.06);font-size:{theme
      .typography.fontSize}px;font-family:{theme.typography.fontFamily};color:{theme.tooltip
      .textColor};z-index:10;display:flex;flex-direction:column;gap:6px;min-width:120px;"
  >
    <div style="display:flex;align-items:center;gap:8px;">
      <span style="width:10px;height:10px;border-radius:3px;background:{info.color};flex-shrink:0;" />
      <span style="font-weight:600;">{info.label}</span>
      <span style="margin-left:auto;font-weight:600;">{format(info.value)}</span>
    </div>
    <div style="position:relative;height:4px;border-radius:2px;background:{theme.tooltip.borderColor};overflow:hidden;">
      <div style="position:absolute;inset:0;width:{meterWidth}%;border-radius:2px;background:{info.color};" />
    </div>
  </div>
{/if}
