// packages/react/src/ui/Marker.tsx
import { useLayoutEffect, useRef } from 'react';

import type { MarkerShape, TimeValue } from '@wick-charts/core';

import { useChartInstance } from '../context';

export interface MarkerProps {
  /** X anchor — epoch ms or a `Date`. */
  time: TimeValue;
  /**
   * Y anchor as a data value. Omit and set {@link MarkerProps.seriesId} to snap
   * the marker to that series' nearest data point at `time`.
   */
  value?: number;
  /** Snap Y to this series' value at `time` when `value` is omitted. Also the default color source. */
  seriesId?: string;
  /** Glyph at the anchor. Default: `'dot'`. Arrows point their tip at the anchor. */
  shape?: MarkerShape;
  /** Reuse the line pulse halo around the anchor. Default: `false`. */
  pulse?: boolean;
  /** Optional text label drawn as a callout chip whose tail points at the anchor. */
  label?: string;
  /** Color override. Falls back to the series color (when `seriesId` is set), then the theme line color. */
  color?: string;
}

/**
 * A point annotation (event marker) pinned to a `time` / `value` — "anomaly
 * opened here", "deploy v1.2.3", "alert resolved". Renders on the chart's
 * overlay canvas and stays out of the series model, so it never shows up in the
 * tooltip, legend, or Y-range autoscale, and is clipped to the plot area.
 *
 * ```tsx
 * <Marker time={openedMs} seriesId="metric" shape="arrow-down" pulse={true} label="broke" color="#f0556a" />
 * ```
 */
export function Marker({ time, value, seriesId, shape, pulse, label, color }: MarkerProps) {
  const chart = useChartInstance();
  const idRef = useRef<string | null>(null);

  // Normalized ms drives the update effect's dep list so a fresh `Date` object
  // for the same instant doesn't trigger a redundant update on every render.
  const timeMs = time instanceof Date ? time.getTime() : time;

  // Register once on mount; tear down on unmount.
  useLayoutEffect(() => {
    const id = chart.addMarker({ time, value, seriesId, shape, pulse, label, color });
    idRef.current = id;

    return () => {
      chart.removeMarker(id);
      idRef.current = null;
    };
  }, [chart]);

  // Push prop changes through to the live marker.
  useLayoutEffect(() => {
    const id = idRef.current;
    if (id === null) return;

    chart.updateMarker(id, { time, value, seriesId, shape, pulse, label, color });
  }, [chart, timeMs, value, seriesId, shape, pulse, label, color]);

  return null;
}

// packages/svelte/src/ui/Marker.svelte
<script lang="ts">
import type { MarkerShape, TimeValue } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from '../context';

/** X anchor — epoch ms or a `Date`. */
export let time: TimeValue;
/** Y anchor as a data value. Omit and set `seriesId` to snap to that series' value at `time`. */
export let value: number | undefined = undefined;
/** Snap Y to this series' value at `time` when `value` is omitted. Also the default color source. */
export let seriesId: string | undefined = undefined;
/** Glyph at the anchor. Default: `'dot'`. Arrows point their tip at the anchor. */
export let shape: MarkerShape | undefined = undefined;
/** Reuse the line pulse halo around the anchor. Default: `false`. */
export let pulse: boolean | undefined = undefined;
/** Optional text label drawn as a callout chip whose tail points at the anchor. */
export let label: string | undefined = undefined;
/** Color override. Falls back to the series color (when `seriesId` is set), then the theme line color. */
export let color: string | undefined = undefined;

const chartStore = getChartContext();
let markerId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;

  markerId = chart.addMarker({ time, value, seriesId, shape, pulse, label, color });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (markerId !== null && chart) chart.removeMarker(markerId);
  markerId = null;
});

// Push prop changes through to the live marker (the first pass runs before
// onMount sets markerId, so it's a guarded no-op).
$: {
  const chart = $chartStore;
  if (markerId !== null && chart) {
    chart.updateMarker(markerId, { time, value, seriesId, shape, pulse, label, color });
  }
}
</script>
