// packages/vue/src/ui/Marker.vue
<script setup lang="ts">
import type { MarkerShape, TimeValue } from '@wick-charts/core';
import { onMounted, onUnmounted, watch } from 'vue';

import { useChartInstance } from '../context';

const props = defineProps<{
  /** X anchor — epoch ms or a `Date`. */
  time: TimeValue;
  /** Y anchor as a data value. Omit and set `seriesId` to snap to that series' value at `time`. */
  value?: number;
  /** Snap Y to this series' value at `time` when `value` is omitted. Also the default color source. */
  seriesId?: string;
  /** Glyph at the anchor. Default: `'dot'`. Arrows point their tip at the anchor. */
  shape?: MarkerShape;
  /** Reuse the line pulse halo around the anchor. Default: `false`. */
  pulse?: boolean;
  /** Optional text label drawn as a callout chip whose tail points at the anchor. */
  label?: string;
  /** Color override. Falls back to the series color (when `seriesId` is set), then the theme line color. */
  color?: string;
}>();

const chart = useChartInstance();
let markerId: string | null = null;

onMounted(() => {
  markerId = chart.addMarker({
    time: props.time,
    value: props.value,
    seriesId: props.seriesId,
    shape: props.shape,
    pulse: props.pulse,
    label: props.label,
    color: props.color,
  });
});

onUnmounted(() => {
  if (markerId !== null) chart.removeMarker(markerId);
  markerId = null;
});

watch(
  () => [props.time, props.value, props.seriesId, props.shape, props.pulse, props.label, props.color],
  () => {
    if (markerId === null) return;

    chart.updateMarker(markerId, {
      time: props.time,
      value: props.value,
      seriesId: props.seriesId,
      shape: props.shape,
      pulse: props.pulse,
      label: props.label,
      color: props.color,
    });
  },
);
</script>

<template><span v-if="false" /></template>

// packages/svelte/src/ui/Marker.svelte
<script lang="ts">
import type { MarkerShape, TimeValue } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from '../context';

/** X anchor — epoch ms or a `Date`. */
export let time: TimeValue;
/** Y anchor as a data value. Omit and set `seriesId` to snap to that series' value at `time`. */
export let value: number | undefined = undefined;
/** Snap Y to this series' value at `time` when `value` is omitted. Also the default color source. */
export let seriesId: string | undefined = undefined;
/** Glyph at the anchor. Default: `'dot'`. Arrows point their tip at the anchor. */
export let shape: MarkerShape | undefined = undefined;
/** Reuse the line pulse halo around the anchor. Default: `false`. */
export let pulse: boolean | undefined = undefined;
/** Optional text label drawn as a callout chip whose tail points at the anchor. */
export let label: string | undefined = undefined;
/** Color override. Falls back to the series color (when `seriesId` is set), then the theme line color. */
export let color: string | undefined = undefined;

const chartStore = getChartContext();
let markerId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;

  markerId = chart.addMarker({ time, value, seriesId, shape, pulse, label, color });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (markerId !== null && chart) chart.removeMarker(markerId);
  markerId = null;
});

// Push prop changes through to the live marker (the first pass runs before
// onMount sets markerId, so it's a guarded no-op).
$: {
  const chart = $chartStore;
  if (markerId !== null && chart) {
    chart.updateMarker(markerId, { time, value, seriesId, shape, pulse, label, color });
  }
}
</script>
