// packages/vue/src/ui/PieLegend.vue
<script setup lang="ts">
import { type ChartInstance, type SliceInfo, type ValueFormatter, formatCompact } from '@wick-charts/core';
import { computed, onMounted, onUnmounted, ref, useSlots } from 'vue';

import { useChartInstance, useTheme } from '../context';

type PieLegendMode = 'value' | 'percent' | 'both';

const props = withDefaults(
  defineProps<{
    /**
     * Owning series id. **Optional** — when omitted, the first visible pie
     * series is picked.
     */
    seriesId?: string;
    /** 'value' shows only the value, 'percent' only the percent, 'both' shows both. Default: 'both'. */
    mode?: PieLegendMode;
    /** Custom formatter for the absolute slice value. */
    format?: ValueFormatter;
  }>(),
  {
    mode: undefined,
    format: undefined,
  },
);

defineSlots<{
  default?(ctx: { slices: readonly SliceInfo[]; mode: PieLegendMode; format: ValueFormatter }): unknown;
}>();

const resolvedMode = computed<PieLegendMode>(() => props.mode ?? 'both');
const resolvedFormat = computed<ValueFormatter>(() => props.format ?? formatCompact);

const chart = useChartInstance();
const themeRef = useTheme();
const slots = useSlots();
const hasCustomSlot = computed(() => typeof slots.default === 'function');

const bump = ref(0);
const handler = () => {
  bump.value++;
};
onMounted(() => {
  chart.on('overlayChange', handler);
  if (chart.getSeriesIds().length > 0) bump.value++;
});
onUnmounted(() => {
  chart.off('overlayChange', handler);
});

function resolvePieSeriesId(c: ChartInstance, explicit: string | undefined): string | null {
  if (explicit !== undefined) return explicit;

  const pies = c.getSeriesIdsByType('pie', { visibleOnly: true });

  return pies.length > 0 ? pies[0] : null;
}

const theme = computed(() => themeRef.value);
const resolvedId = computed<string | null>(() => {
  void bump.value;

  return resolvePieSeriesId(chart, props.seriesId);
});
const slices = computed<readonly SliceInfo[]>(() => {
  void bump.value;
  if (resolvedId.value === null) return [];

  return chart.getSliceInfo(resolvedId.value) ?? [];
});
</script>

<template>
  <slot
    v-if="hasCustomSlot && slices.length > 0"
    :slices="slices"
    :mode="resolvedMode"
    :format="resolvedFormat"
  />
  <div
    v-else-if="slices.length > 0"
    :style="{
      display: 'flex',
      flexDirection: 'column',
      gap: '6px',
      padding: '8px 12px',
      fontFamily: theme.typography.fontFamily,
      fontSize: theme.typography.fontSize + 'px',
      color: theme.tooltip.textColor,
      pointerEvents: 'auto',
    }"
  >
    <div
      v-for="(slice, i) in slices"
      :key="i"
      :style="{ display: 'flex', alignItems: 'center', gap: '10px' }"
    >
      <span :style="{ width: '10px', height: '10px', borderRadius: '50%', background: slice.color, flexShrink: 0 }" />
      <span :style="{ flex: 1, opacity: 0.8 }">{{ slice.label }}</span>
      <span
        v-if="resolvedMode === 'value' || resolvedMode === 'both'"
        :style="{
          fontWeight: 600,
          fontVariantNumeric: 'tabular-nums',
          minWidth: resolvedMode === 'value' ? '40px' : undefined,
          textAlign: 'right',
        }"
      >
        {{ resolvedFormat(slice.value) }}
      </span>
      <span
        v-if="resolvedMode === 'percent' || resolvedMode === 'both'"
        :style="{
          opacity: resolvedMode === 'percent' ? 1 : 0.5,
          fontWeight: resolvedMode === 'percent' ? 600 : 400,
          fontSize: (resolvedMode === 'percent' ? theme.typography.fontSize : theme.typography.axisFontSize) + 'px',
          fontVariantNumeric: 'tabular-nums',
          minWidth: '40px',
          textAlign: 'right',
        }"
      >
        {{ slice.percent.toFixed(1) }}%
      </span>
    </div>
  </div>
</template>

// packages/svelte/src/ui/PieLegend.svelte
<script lang="ts">
import { type ChartInstance, type SliceInfo, type ValueFormatter, formatCompact } from '@wick-charts/core';
import { onDestroy } from 'svelte';

import { getChartContext, getThemeContext } from '../context';

type PieLegendMode = 'value' | 'percent' | 'both';

/**
 * Owning series id. **Optional** — when omitted, the first visible pie
 * series is picked.
 */
export let seriesId: string | undefined = undefined;
/** 'value' shows only the value, 'percent' only the percent, 'both' shows both. Default: 'both'. */
export let mode: PieLegendMode | undefined = undefined;
/** Custom formatter for the absolute slice value. */
export let format: ValueFormatter | undefined = undefined;

$: resolvedMode = (mode ?? 'both') as PieLegendMode;
$: resolvedFormat = (format ?? formatCompact) as ValueFormatter;

const chartStore = getChartContext();
const themeStore = getThemeContext();

let bump = 0;
let overlayUnsub: (() => void) | null = null;

$: {
  const c = $chartStore;
  if (c && !overlayUnsub) {
    const handler = () => {
      bump++;
    };
    c.on('overlayChange', handler);
    overlayUnsub = () => c.off('overlayChange', handler);
    if (c.getSeriesIds().length > 0) bump++;
  }
}

onDestroy(() => {
  overlayUnsub?.();
});

function resolvePieSeriesId(c: ChartInstance, explicit: string | undefined): string | null {
  if (explicit !== undefined) return explicit;

  const pies = c.getSeriesIdsByType('pie', { visibleOnly: true });

  return pies.length > 0 ? pies[0] : null;
}

$: chart = $chartStore;
$: theme = $themeStore;
$: resolvedId = chart && bump >= 0 ? resolvePieSeriesId(chart, seriesId) : null;
$: slices = ((chart && resolvedId !== null ? chart.getSliceInfo(resolvedId) : null) ?? []) as readonly SliceInfo[];
</script>

{#if slices.length > 0 && theme}
  {#if $$slots.default}
    <slot slices={slices} mode={resolvedMode} format={resolvedFormat} />
  {:else}
    <div
      style="display:flex;flex-direction:column;gap:6px;padding:8px 12px;font-family:{theme.typography.fontFamily};font-size:{theme.typography.fontSize}px;color:{theme.tooltip.textColor};pointer-events:auto;"
    >
      {#each slices as slice, i (i)}
        <div style="display:flex;align-items:center;gap:10px;">
          <span style="width:10px;height:10px;border-radius:50%;background:{slice.color};flex-shrink:0;" />
          <span style="flex:1;opacity:0.8;">{slice.label}</span>
          {#if resolvedMode === 'value' || resolvedMode === 'both'}
            <span
              style="font-weight:600;font-variant-numeric:tabular-nums;{resolvedMode === 'value'
                ? 'min-width:40px;text-align:right;'
                : ''}"
            >
              {resolvedFormat(slice.value)}
            </span>
          {/if}
          {#if resolvedMode === 'percent' || resolvedMode === 'both'}
            <span
              style="opacity:{resolvedMode === 'percent'
                ? 1
                : 0.5};font-weight:{resolvedMode === 'percent'
                ? 600
                : 400};font-size:{resolvedMode === 'percent'
                ? theme.typography.fontSize
                : theme.typography.axisFontSize}px;font-variant-numeric:tabular-nums;min-width:40px;text-align:right;"
            >
              {slice.percent.toFixed(1)}%
            </span>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
{/if}
