// packages/vue/src/ui/TimeRegion.vue
<script setup lang="ts">
import type { TimeRegionEnd, TimeValue } from '@wick-charts/core';
import { onMounted, onUnmounted, watch } from 'vue';

import { useChartInstance } from '../context';

const props = defineProps<{
  /** Left edge — epoch ms or a `Date`. */
  from: TimeValue;
  /** Right edge — epoch ms or a `Date`. Omit (or pass `'now'`) for an open-ended band to the right edge. */
  to?: TimeRegionEnd;
  /** Band fill — any CSS color, typically translucent. Default: a faint tint of `color`. */
  fill?: string;
  /** Optional text label drawn in an annotation chip at the top of the band. */
  label?: string;
  /** Edge-line and label-chip accent. Default: the theme's muted axis text color. */
  color?: string;
}>();

const chart = useChartInstance();
let regionId: string | null = null;

onMounted(() => {
  regionId = chart.addRegion({
    from: props.from,
    to: props.to,
    fill: props.fill,
    label: props.label,
    color: props.color,
  });
});

onUnmounted(() => {
  if (regionId !== null) chart.removeRegion(regionId);
  regionId = null;
});

watch(
  () => [props.from, props.to, props.fill, props.label, props.color],
  () => {
    if (regionId === null) return;

    chart.updateRegion(regionId, {
      from: props.from,
      to: props.to,
      fill: props.fill,
      label: props.label,
      color: props.color,
    });
  },
);
</script>

<template><span v-if="false" /></template>

// packages/svelte/src/ui/TimeRegion.svelte
<script lang="ts">
import type { TimeRegionEnd, TimeValue } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from '../context';

/** Left edge — epoch ms or a `Date`. */
export let from: TimeValue;
/** Right edge — epoch ms or a `Date`. Omit (or pass `'now'`) for an open-ended band to the right edge. */
export let to: TimeRegionEnd | undefined = undefined;
/** Band fill — any CSS color, typically translucent. Default: a faint tint of `color`. */
export let fill: string | undefined = undefined;
/** Optional text label drawn in an annotation chip at the top of the band. */
export let label: string | undefined = undefined;
/** Edge-line and label-chip accent. Default: the theme's muted axis text color. */
export let color: string | undefined = undefined;

const chartStore = getChartContext();
let regionId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;

  regionId = chart.addRegion({ from, to, fill, label, color });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (regionId !== null && chart) chart.removeRegion(regionId);
  regionId = null;
});

// Push prop changes through to the live region (the first pass runs before
// onMount sets regionId, so it's a guarded no-op).
$: {
  const chart = $chartStore;
  if (regionId !== null && chart) {
    chart.updateRegion(regionId, { from, to, fill, label, color });
  }
}
</script>
