// packages/vue/src/ui/Legend.vue
<script setup lang="ts">
import { computed, inject, onMounted, onUnmounted, ref } from 'vue';

import { LegendAnchorKey, LegendRightAnchorKey, ThemeKey, useChartInstance } from '../context';

export interface LegendItem {
  label: string;
  color: string;
}

interface ResolvedItem extends LegendItem {
  seriesId: string;
  layerIndex: number;
  isLayer: boolean;
}

const props = withDefaults(
  defineProps<{
    items?: LegendItem[];
    position?: 'bottom' | 'right';
    mode?: 'toggle' | 'solo';
  }>(),
  {
    position: 'bottom',
    mode: 'toggle',
  },
);

const chart = useChartInstance();
const theme = inject(ThemeKey);
const bottomAnchor = inject(LegendAnchorKey);
const rightAnchor = inject(LegendRightAnchorKey);

if (!theme) {
  throw new Error('<Legend> must be used within <ChartContainer>: missing ThemeKey.');
}
if (!bottomAnchor || !rightAnchor) {
  throw new Error('<Legend> must be used within <ChartContainer>: missing legend anchors.');
}

const anchor = computed(() => (props.position === 'right' ? rightAnchor.value : bottomAnchor.value));

const disabled = ref<Set<number>>(new Set());
const bump = ref(0);

const seriesChangeHandler = () => {
  bump.value++;
  disabled.value = new Set();
};
const dataUpdateHandler = () => {
  bump.value++;
};

onMounted(() => {
  chart.on('seriesChange', seriesChangeHandler);
  chart.on('dataUpdate', dataUpdateHandler);
  if (chart.getSeriesIds().length > 0) bump.value++;
});

onUnmounted(() => {
  chart.off('seriesChange', seriesChangeHandler);
  chart.off('dataUpdate', dataUpdateHandler);
});

const resolved = computed<ResolvedItem[]>(() => {
  void bump.value;
  if (props.items) {
    return props.items.map((item, i) => ({ ...item, seriesId: '', layerIndex: i, isLayer: false }));
  }
  const result: ResolvedItem[] = [];
  for (const id of chart.getSeriesIds()) {
    const layers = chart.getSeriesLayers(id);
    if (layers) {
      const baseLabel = chart.getSeriesLabel(id);
      for (let i = 0; i < layers.length; i++) {
        result.push({
          label: baseLabel ? `${baseLabel} ${i + 1}` : `Series ${i + 1}`,
          color: layers[i].color,
          seriesId: id,
          layerIndex: i,
          isLayer: true,
        });
      }
    } else {
      const color = chart.getSeriesColor(id);
      const label = chart.getSeriesLabel(id);
      if (color) result.push({ label: label ?? 'Series', color, seriesId: id, layerIndex: 0, isLayer: false });
    }
  }
  return result;
});

function apply(next: Set<number>) {
  disabled.value = next;
  const list = resolved.value;
  chart.batch(() => {
    for (let i = 0; i < list.length; i++) {
      const item = list[i];
      if (!item.seriesId) continue;
      if (item.isLayer) {
        chart.setLayerVisible(item.seriesId, item.layerIndex, !next.has(i));
      } else {
        chart.setSeriesVisible(item.seriesId, !next.has(i));
      }
    }
  });
}

function handleClick(index: number) {
  const list = resolved.value;
  if (props.mode === 'solo') {
    const allOthersOff = list.every((_, i) => i === index || disabled.value.has(i));
    if (allOthersOff) {
      apply(new Set());
    } else {
      const next = new Set(list.map((_, i) => i));
      next.delete(index);
      apply(next);
    }
  } else {
    const s = new Set(disabled.value);
    if (s.has(index)) s.delete(index);
    else s.add(index);
    apply(s);
  }
}
</script>

<template>
  <Teleport v-if="anchor && theme && resolved.length > 0" :to="anchor">
    <div
      :data-legend="position"
      :style="{
        display: 'flex',
        flexDirection: position === 'right' ? 'column' : 'row',
        flexWrap: 'wrap',
        gap: position === 'right' ? '6px' : '14px',
        padding: position === 'right' ? '8px 6px' : '6px 8px',
        alignItems: position === 'right' ? 'flex-start' : 'center',
        justifyContent: position === 'right' ? 'flex-start' : 'center',
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.typography.axisFontSize + 'px',
        color: theme.axis.textColor,
        pointerEvents: 'auto',
        flexShrink: 0,
      }"
    >
      <div
        v-for="(item, i) in resolved"
        :key="i"
        @click="item.seriesId ? handleClick(i) : undefined"
        :style="{
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
          cursor: item.seriesId ? 'pointer' : 'default',
          opacity: disabled.has(i) ? 0.35 : 1,
          transition: 'opacity 0.15s ease',
          userSelect: 'none',
        }"
      >
        <span
          :style="{
            width: '8px',
            height: '8px',
            borderRadius: '2px',
            background: item.color,
            flexShrink: 0,
          }"
        />
        <span style="white-space: nowrap">{{ item.label }}</span>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/ui/Legend.tsx
import { useEffect, useLayoutEffect, useState } from 'react';

import { useChartInstance } from '../context';
import { useTheme } from '../ThemeContext';

export interface LegendItem {
  label: string;
  color: string;
}

interface ResolvedItem extends LegendItem {
  seriesId: string;
  layerIndex: number;
  isLayer: boolean; // true = layer within multi-layer, false = whole series
}

export interface LegendProps {
  /** Override auto-detected items. When omitted, derived from series layers. */
  items?: LegendItem[];
  /** Layout position. Default: 'bottom'. */
  position?: 'bottom' | 'right';
  /**
   * Click behavior:
   * - `'toggle'` — click toggles individual items on/off (default)
   * - `'solo'` — click shows only that item; click again shows all
   */
  mode?: 'toggle' | 'solo';
}

export function Legend({ items, position = 'bottom', mode = 'toggle' }: LegendProps) {
  const chart = useChartInstance();
  const theme = useTheme();
  const [disabled, setDisabled] = useState<Set<number>>(new Set());
  const [, bump] = useState(0);

  useLayoutEffect(() => {
    const onSeriesChange = () => {
      bump((n) => n + 1);
      setDisabled(new Set()); // reset toggles — series list changed
    };
    const onDataUpdate = () => bump((n) => n + 1);
    chart.on('seriesChange', onSeriesChange);
    chart.on('dataUpdate', onDataUpdate);
    // Catch-up: series may already be registered by sibling useLayoutEffects
    // that fired earlier in tree order. Bump so the next synchronous re-render
    // picks them up before the browser paints.
    if (chart.getSeriesIds().length > 0) bump((n) => n + 1);
    return () => {
      chart.off('seriesChange', onSeriesChange);
      chart.off('dataUpdate', onDataUpdate);
    };
  }, [chart]);

  const resolved: ResolvedItem[] =
    items?.map((item, i) => ({ ...item, seriesId: '', layerIndex: i, isLayer: false })) ??
    (() => {
      const result: ResolvedItem[] = [];
      for (const id of chart.getSeriesIds()) {
        const layers = chart.getSeriesLayers(id);
        if (layers) {
          const baseLabel = chart.getSeriesLabel(id);
          for (let i = 0; i < layers.length; i++) {
            result.push({
              label: baseLabel ? `${baseLabel} ${i + 1}` : `Series ${i + 1}`,
              color: layers[i].color,
              seriesId: id,
              layerIndex: i,
              isLayer: true,
            });
          }
        } else {
          const color = chart.getSeriesColor(id);
          const label = chart.getSeriesLabel(id);
          if (color) result.push({ label: label ?? 'Series', color, seriesId: id, layerIndex: 0, isLayer: false });
        }
      }
      return result;
    })();

  if (resolved.length === 0) return null;

  const apply = (next: Set<number>) => {
    setDisabled(next);
    chart.batch(() => {
      for (let i = 0; i < resolved.length; i++) {
        const item = resolved[i];
        if (!item.seriesId) continue;
        if (item.isLayer) {
          chart.setLayerVisible(item.seriesId, item.layerIndex, !next.has(i));
        } else {
          chart.setSeriesVisible(item.seriesId, !next.has(i));
        }
      }
    });
  };

  const handleClick = (index: number) => {
    if (mode === 'solo') {
      // Solo: if already solo'd on this one → show all, otherwise solo it
      const allOthersOff = resolved.every((_, i) => i === index || disabled.has(i));
      if (allOthersOff) {
        apply(new Set());
      } else {
        const next = new Set(resolved.map((_, i) => i));
        next.delete(index);
        apply(next);
      }
    } else {
      // Toggle
      const s = new Set(disabled);
      if (s.has(index)) s.delete(index);
      else s.add(index);
      apply(s);
    }
  };

  const isRight = position === 'right';

  return (
    <div
      data-legend={position}
      style={{
        display: 'flex',
        flexDirection: isRight ? 'column' : 'row',
        flexWrap: 'wrap',
        gap: isRight ? 6 : 14,
        padding: isRight ? '8px 6px' : '6px 8px',
        alignItems: isRight ? 'flex-start' : 'center',
        justifyContent: isRight ? 'flex-start' : 'center',
        fontFamily: theme.typography.fontFamily,
        fontSize: theme.typography.axisFontSize,
        color: theme.axis.textColor,
        pointerEvents: 'auto',
        flexShrink: 0,
      }}
    >
      {resolved.map((item, i) => {
        const isDisabled = disabled.has(i);
        const interactive = !!item.seriesId;
        return (
          <div
            key={i}
            onClick={interactive ? () => handleClick(i) : undefined}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              cursor: interactive ? 'pointer' : 'default',
              opacity: isDisabled ? 0.35 : 1,
              transition: 'opacity 0.15s ease',
              userSelect: 'none',
            }}
          >
            <span
              style={{
                width: 8,
                height: 8,
                borderRadius: 2,
                background: item.color,
                flexShrink: 0,
              }}
            />
            <span style={{ whiteSpace: 'nowrap' }}>
              {item.label}
            </span>
          </div>
        );
      })}
    </div>
  );
}
