// packages/vue/src/ui/Tooltip.vue
<script setup lang="ts">
import { computed } from 'vue';
import { formatDate, formatTime, type LineData, type OHLCData } from '@wick-charts/core';
import { useChartInstance } from '../context';
import { useCrosshairPosition, useLastPrice } from '../composables';

type TooltipSort = 'none' | 'asc' | 'desc';

interface SeriesSnapshot {
  id: string;
  label?: string;
  data: OHLCData | LineData;
  color: string;
}

const props = withDefaults(defineProps<{
  seriesId?: string;
  sort?: TooltipSort;
}>(), {
  sort: 'none',
});

const chart = useChartInstance();
const crosshair = useCrosshairPosition(chart);

const targetIds = computed(() => {
  if (props.seriesId) return [props.seriesId];
  return chart.getSeriesIds();
});

const primaryId = computed(() => targetIds.value[0] ?? '');
const lastPrice = useLastPrice(chart, primaryId.value);

const theme = computed(() => chart.getTheme());
const dataInterval = computed(() => chart.getDataInterval());

function sortSnapshots(snapshots: SeriesSnapshot[], sort: TooltipSort): SeriesSnapshot[] {
  if (sort === 'none' || snapshots.length <= 1) return snapshots;
  return [...snapshots].sort((a, b) => {
    const av = 'value' in a.data ? (a.data as LineData).value : (a.data as OHLCData).close;
    const bv = 'value' in b.data ? (b.data as LineData).value : (b.data as OHLCData).close;
    return sort === 'asc' ? av - bv : bv - av;
  });
}

function formatVolume(v: number): string {
  if (v >= 1e9) return (v / 1e9).toFixed(2) + 'B';
  if (v >= 1e6) return (v / 1e6).toFixed(2) + 'M';
  if (v >= 1e3) return (v / 1e3).toFixed(1) + 'K';
  return v.toFixed(0);
}

const snapshots = computed(() => {
  // Access reactive dependencies
  void lastPrice.value;

  const hoverSnapshots: SeriesSnapshot[] = [];
  if (crosshair.value) {
    for (const id of targetIds.value) {
      const d = chart.getDataAtTime(id, crosshair.value.time);
      if (d) {
        hoverSnapshots.push({
          id,
          label: chart.getSeriesLabel(id),
          data: d,
          color: chart.getSeriesColor(id) ?? '#888',
        });
      }
    }
  }

  const lastSnapshots: SeriesSnapshot[] = [];
  for (const id of targetIds.value) {
    const d = chart.getLastData(id);
    if (d) {
      lastSnapshots.push({
        id,
        label: chart.getSeriesLabel(id),
        data: d,
        color: chart.getSeriesColor(id) ?? '#888',
      });
    }
  }

  const raw = hoverSnapshots.length > 0 ? hoverSnapshots : lastSnapshots;
  return sortSnapshots(raw, props.sort);
});

const hoverSnapshots = computed(() => {
  if (!crosshair.value) return [];
  const result: SeriesSnapshot[] = [];
  for (const id of targetIds.value) {
    const d = chart.getDataAtTime(id, crosshair.value.time);
    if (d) {
      result.push({
        id,
        label: chart.getSeriesLabel(id),
        data: d,
        color: chart.getSeriesColor(id) ?? '#888',
      });
    }
  }
  return sortSnapshots(result, props.sort);
});

const displayTime = computed(() => {
  if (snapshots.value.length === 0) return 0;
  return snapshots.value[0].data.time;
});

const floatingPos = computed(() => {
  if (!crosshair.value || hoverSnapshots.value.length === 0) return null;
  const mediaSize = chart.getMediaSize();
  const hasOHLC = hoverSnapshots.value.some((s) => 'open' in s.data);
  const lineCount = hoverSnapshots.value.filter((s) => !('open' in s.data)).length;

  const tooltipWidth = 160;
  const tooltipHeight = hasOHLC ? 140 : 40 + lineCount * 22;
  const offsetX = 16;
  const offsetY = 16;
  const chartWidth = mediaSize.width - chart.yAxisWidth;
  const chartHeight = mediaSize.height - chart.xAxisHeight;

  const left =
    crosshair.value.mediaX + offsetX + tooltipWidth > chartWidth
      ? crosshair.value.mediaX - offsetX - tooltipWidth
      : crosshair.value.mediaX + offsetX;
  const top =
    crosshair.value.mediaY + offsetY + tooltipHeight > chartHeight
      ? crosshair.value.mediaY - offsetY - tooltipHeight
      : crosshair.value.mediaY + offsetY;

  return { left, top };
});

function isOHLC(data: OHLCData | LineData): data is OHLCData {
  return 'open' in data;
}
</script>

<template>
  <template v-if="snapshots.length > 0">
    <!-- Compact legend (top-left, always visible) -->
    <div
      :style="{
        position: 'absolute',
        top: '24px',
        left: '8px',
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        flexWrap: 'wrap',
        maxWidth: '70%',
        fontSize: theme.typography.fontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        opacity: crosshair ? 1 : 0.6,
        transition: 'opacity 0.2s ease',
      }"
    >
      <span :style="{ color: theme.axis.textColor, marginRight: '2px' }">
        {{ formatTime(displayTime, dataInterval) }}
      </span>
      <template v-for="s in snapshots" :key="s.id">
        <!-- OHLC legend -->
        <span v-if="isOHLC(s.data)" :style="{ display: 'inline-flex', alignItems: 'center', gap: '4px' }">
          <template v-for="field in (['O', 'H', 'L', 'C'] as const)" :key="field">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">{{ field }}</span>
            <span
              :style="{
                color: (s.data as OHLCData).close >= (s.data as OHLCData).open ? theme.candlestick.upColor : theme.candlestick.downColor,
                fontWeight: 500,
                marginLeft: '2px',
              }"
            >
              {{ ({ O: (s.data as OHLCData).open, H: (s.data as OHLCData).high, L: (s.data as OHLCData).low, C: (s.data as OHLCData).close })[field].toFixed(2) }}
            </span>
          </template>
          <template v-if="(s.data as OHLCData).volume != null">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">V</span>
            <span :style="{ color: theme.axis.textColor, fontWeight: 500, marginLeft: '2px' }">
              {{ formatVolume((s.data as OHLCData).volume!) }}
            </span>
          </template>
        </span>
        <!-- Line legend -->
        <span v-else :style="{ display: 'inline-flex', alignItems: 'center', gap: '3px' }">
          <span
            :style="{
              width: '6px',
              height: '6px',
              borderRadius: '50%',
              background: s.color,
              flexShrink: 0,
            }"
          />
          <span :style="{ color: s.color, fontWeight: 500 }">
            {{ (s.data as LineData).value.toFixed(2) }}
          </span>
        </span>
      </template>
    </div>

    <!-- Floating tooltip (near cursor, only on hover) -->
    <div
      v-if="crosshair && hoverSnapshots.length > 0 && floatingPos"
      :style="{
        position: 'absolute',
        left: floatingPos.left + 'px',
        top: floatingPos.top + 'px',
        pointerEvents: 'none',
        background: theme.tooltip.background,
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        border: '1px solid ' + theme.tooltip.borderColor,
        borderRadius: '8px',
        padding: '10px 14px',
        boxShadow: '0 4px 16px rgba(0,0,0,0.1), 0 1px 4px rgba(0,0,0,0.06)',
        fontSize: theme.typography.tooltipFontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        color: theme.tooltip.textColor,
        minWidth: '140px',
        zIndex: 10,
        transition: 'opacity 0.15s ease',
      }"
    >
      <!-- Time header -->
      <div
        :style="{
          fontSize: theme.typography.axisFontSize + 'px',
          color: theme.axis.textColor,
          marginBottom: '8px',
          paddingBottom: '6px',
          borderBottom: '1px solid ' + theme.tooltip.borderColor,
          letterSpacing: '0.02em',
        }"
      >
        {{ formatDate(displayTime) }} {{ formatTime(displayTime, dataInterval) }}
      </div>

      <template v-for="s in snapshots" :key="s.id">
        <!-- OHLC floating -->
        <div
          v-if="isOHLC(s.data)"
          :style="{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '4px 12px' }"
        >
          <template v-for="row in [
            { label: 'Open', val: (s.data as OHLCData).open },
            { label: 'High', val: (s.data as OHLCData).high },
            { label: 'Low', val: (s.data as OHLCData).low },
            { label: 'Close', val: (s.data as OHLCData).close },
          ]" :key="row.label">
            <span :style="{ opacity: 0.5 }">{{ row.label }}</span>
            <span
              :style="{
                fontWeight: 600,
                color: (s.data as OHLCData).close >= (s.data as OHLCData).open
                  ? theme.candlestick.upColor
                  : theme.candlestick.downColor,
                textAlign: 'right',
              }"
            >{{ row.val.toFixed(2) }}</span>
          </template>
          <template v-if="(s.data as OHLCData).volume != null">
            <span :style="{ opacity: 0.5 }">Volume</span>
            <span :style="{ fontWeight: 600, color: theme.tooltip.textColor, textAlign: 'right' }">
              {{ formatVolume((s.data as OHLCData).volume!) }}
            </span>
          </template>
        </div>
        <!-- Line floating -->
        <div
          v-else
          :style="{ display: 'flex', alignItems: 'center', gap: '8px', padding: '2px 0' }"
        >
          <span
            :style="{
              width: '8px',
              height: '8px',
              borderRadius: '50%',
              background: s.color,
              flexShrink: 0,
            }"
          />
          <span :style="{ opacity: 0.6, flex: '1' }">{{ s.label ?? 'Value' }}</span>
          <span :style="{ fontWeight: 600, color: s.color }">
            {{ (s.data as LineData).value.toFixed(2) }}
          </span>
        </div>
      </template>
    </div>
  </template>
</template>

// packages/react/src/ui/Tooltip.tsx
import { useEffect, useState } from 'react';

import { type LineData, type OHLCData, formatDate, formatTime } from '@wick-charts/core';

import { useChartInstance } from '../context';
import { useCrosshairPosition } from '../store-bridge';

/** Sort order for multi-series tooltip values. */
export type TooltipSort = 'none' | 'asc' | 'desc';

/**
 * Props for the {@link Tooltip} component.
 * By default shows all series. Use `seriesId` to show one, or `sort` to order values.
 */
export interface TooltipProps {
  /** Show only this series. When omitted, show all series. */
  seriesId?: string;
  /** Sort order for line values when showing all series (default: 'none'). */
  sort?: TooltipSort;
  /** Show the compact legend strip in the top-left corner (default: true). */
  legend?: boolean;
}

/** Snapshot of a single series at a point in time, used for tooltip rendering. */
interface SeriesSnapshot {
  id: string;
  label?: string;
  data: OHLCData | LineData;
  color: string;
}

function sortSnapshots(snapshots: SeriesSnapshot[], sort: TooltipSort): SeriesSnapshot[] {
  if (sort === 'none' || snapshots.length <= 1) return snapshots;
  return [...snapshots].sort((a, b) => {
    const av = 'value' in a.data ? (a.data as LineData).value : (a.data as OHLCData).close;
    const bv = 'value' in b.data ? (b.data as LineData).value : (b.data as OHLCData).close;
    return sort === 'asc' ? av - bv : bv - av;
  });
}

/**
 * Two-part tooltip:
 * 1. Compact legend always visible in top-left
 * 2. Floating glass tooltip near cursor on hover
 */
export function Tooltip({ seriesId, sort = 'none', legend = true }: TooltipProps) {
  const chart = useChartInstance();
  const crosshair = useCrosshairPosition(chart);

  // Determine which series to display — getSeriesIds() is internally cached
  const targetIds = seriesId ? [seriesId] : chart.getSeriesIds();

  // Re-render on data updates (not viewport — tooltip content doesn't depend on pan/zoom)
  const [, bumpTooltip] = useState(0);
  useEffect(() => {
    const handler = () => bumpTooltip((n) => n + 1);
    chart.on('dataUpdate', handler);
    return () => chart.off('dataUpdate', handler);
  }, [chart]);

  // Gather hover data for all target series
  const hoverSnapshots: SeriesSnapshot[] = [];
  if (crosshair) {
    for (const id of targetIds) {
      const layers = chart.getLayerSnapshots(id, crosshair.time);
      if (layers) {
        for (let i = 0; i < layers.length; i++) {
          hoverSnapshots.push({
            id: `${id}_layer${i}`,
            label: chart.getSeriesLabel(id),
            data: { time: crosshair.time, value: layers[i].value } as LineData,
            color: layers[i].color,
          });
        }
      } else {
        const d = chart.getDataAtTime(id, crosshair.time);
        if (d)
          hoverSnapshots.push({
            id,
            label: chart.getSeriesLabel(id),
            data: d,
            color: chart.getSeriesColor(id) ?? '#888',
          });
      }
    }
  }

  // Gather last-known data for all target series (shown when not hovering) — only when needed
  let raw: SeriesSnapshot[];
  if (hoverSnapshots.length > 0) {
    raw = hoverSnapshots;
  } else {
    const lastSnapshots: SeriesSnapshot[] = [];
    for (const id of targetIds) {
      const d = chart.getLastData(id);
      if (!d) continue;
      const layers = chart.getLayerSnapshots(id, d.time);
      if (layers) {
        for (let i = 0; i < layers.length; i++) {
          lastSnapshots.push({
            id: `${id}_layer${i}`,
            label: chart.getSeriesLabel(id),
            data: { time: d.time, value: layers[i].value } as LineData,
            color: layers[i].color,
          });
        }
      } else {
        lastSnapshots.push({ id, label: chart.getSeriesLabel(id), data: d, color: chart.getSeriesColor(id) ?? '#888' });
      }
    }
    raw = lastSnapshots;
  }
  const snapshots = sortSnapshots(raw, sort);

  const theme = chart.getTheme();
  if (snapshots.length === 0) return null;

  const dataInterval = chart.getDataInterval();
  const mediaSize = chart.getMediaSize();
  const displayTime = snapshots[0].data.time;

  return (
    <>
      {/* ── Compact legend (below chart title) ── */}
      {legend && (
        <div
          style={{
            position: 'absolute',
            top: 24,
            left: 8,
            pointerEvents: 'none',
            display: 'flex',
            alignItems: 'center',
            gap: 4,
            flexWrap: 'wrap',
            maxWidth: '70%',
            fontSize: theme.typography.fontSize,
            fontFamily: theme.typography.fontFamily,
            fontVariantNumeric: 'tabular-nums',
            opacity: crosshair ? 1 : 0.6,
            transition: 'opacity 0.2s ease',
          }}
        >
          <span style={{ color: theme.axis.textColor, marginRight: 2 }}>{formatTime(displayTime, dataInterval)}</span>
          {snapshots.map((s) => {
            const isOHLC = 'open' in s.data;
            if (isOHLC) {
              const ohlc = s.data as OHLCData;
              const isUp = ohlc.close >= ohlc.open;
              const c = isUp ? theme.candlestick.upColor : theme.candlestick.downColor;
              return (
                <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                  <LegendItem label="O" value={ohlc.open} color={c} dim={theme.axis.textColor} />
                  <LegendItem label="H" value={ohlc.high} color={c} dim={theme.axis.textColor} />
                  <LegendItem label="L" value={ohlc.low} color={c} dim={theme.axis.textColor} />
                  <LegendItem label="C" value={ohlc.close} color={c} dim={theme.axis.textColor} />
                  {ohlc.volume != null && (
                    <LegendItem
                      label="V"
                      value={ohlc.volume}
                      color={theme.axis.textColor}
                      dim={theme.axis.textColor}
                      volume
                    />
                  )}
                </span>
              );
            }
            const line = s.data as LineData;
            return (
              <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 3 }}>
                <span
                  style={{
                    width: 6,
                    height: 6,
                    borderRadius: '50%',
                    background: s.color,
                    flexShrink: 0,
                  }}
                />
                <span style={{ color: s.color, fontWeight: 500 }}>{line.value.toFixed(2)}</span>
              </span>
            );
          })}
        </div>
      )}

      {/* ── Floating tooltip (near cursor, only on hover) ── */}
      {crosshair && hoverSnapshots.length > 0 && (
        <FloatingTooltip
          snapshots={snapshots}
          x={crosshair.mediaX}
          y={crosshair.mediaY}
          chartWidth={mediaSize.width - chart.yAxisWidth}
          chartHeight={mediaSize.height - chart.xAxisHeight}
          theme={theme}
          dataInterval={dataInterval}
        />
      )}
    </>
  );
}

function LegendItem({
  label,
  value,
  color,
  dim,
  volume,
}: {
  label: string;
  value: number;
  color: string;
  dim: string;
  volume?: boolean;
}) {
  return (
    <>
      <span style={{ color: dim, opacity: 0.5, marginLeft: 5 }}>{label}</span>
      <span style={{ color, fontWeight: 500, marginLeft: 2 }}>{volume ? formatVolume(value) : value.toFixed(2)}</span>
    </>
  );
}

function FloatingTooltip({
  snapshots,
  x,
  y,
  chartWidth,
  chartHeight,
  theme,
  dataInterval,
}: {
  snapshots: SeriesSnapshot[];
  x: number;
  y: number;
  chartWidth: number;
  chartHeight: number;
  theme: any;
  dataInterval: number;
}) {
  const hasOHLC = snapshots.some((s) => 'open' in s.data);
  const lineCount = snapshots.filter((s) => !('open' in s.data)).length;

  const tooltipWidth = 160;
  const tooltipHeight = hasOHLC ? 140 : 40 + lineCount * 22;
  const offsetX = 16;
  const offsetY = 16;

  const left = x + offsetX + tooltipWidth > chartWidth ? x - offsetX - tooltipWidth : x + offsetX;
  const top = y + offsetY + tooltipHeight > chartHeight ? y - offsetY - tooltipHeight : y + offsetY;

  const bg = theme.tooltip.background;
  const border = theme.tooltip.borderColor;
  const shadow = '0 4px 16px rgba(0,0,0,0.1), 0 1px 4px rgba(0,0,0,0.06)';

  const displayTime = snapshots[0].data.time;

  return (
    <div
      style={{
        position: 'absolute',
        left,
        top,
        pointerEvents: 'none',
        background: bg,
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        border: `1px solid ${border}`,
        borderRadius: 8,
        padding: '10px 14px',
        boxShadow: shadow,
        fontSize: theme.typography.tooltipFontSize,
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        color: theme.tooltip.textColor,
        minWidth: 140,
        zIndex: 10,
        transition: 'opacity 0.15s ease',
      }}
    >
      {/* Time header */}
      <div
        style={{
          fontSize: theme.typography.axisFontSize,
          color: theme.axis.textColor,
          marginBottom: 8,
          paddingBottom: 6,
          borderBottom: `1px solid ${border}`,
          letterSpacing: '0.02em',
        }}
      >
        {formatDate(displayTime)} {formatTime(displayTime, dataInterval)}
      </div>

      {snapshots.map((s) => {
        const isOHLC = 'open' in s.data;
        if (isOHLC) {
          const ohlc = s.data as OHLCData;
          const isUp = ohlc.close >= ohlc.open;
          const upColor = theme.candlestick.upColor;
          const downColor = theme.candlestick.downColor;
          const valColor = isUp ? upColor : downColor;
          return (
            <div key={s.id} style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '4px 12px' }}>
              <TooltipRow label="Open" value={ohlc.open} color={valColor} />
              <TooltipRow label="High" value={ohlc.high} color={valColor} />
              <TooltipRow label="Low" value={ohlc.low} color={valColor} />
              <TooltipRow label="Close" value={ohlc.close} color={valColor} />
              {ohlc.volume != null && (
                <TooltipRow label="Volume" value={ohlc.volume} color={theme.tooltip.textColor} volume />
              )}
            </div>
          );
        }
        const line = s.data as LineData;
        return (
          <div key={s.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '2px 0' }}>
            <span
              style={{
                width: 8,
                height: 8,
                borderRadius: '50%',
                background: s.color,
                flexShrink: 0,
              }}
            />
            <span style={{ opacity: 0.6, flex: 1 }}>{s.label ?? 'Value'}</span>
            <span style={{ fontWeight: 600, color: s.color }}>{line.value.toFixed(2)}</span>
          </div>
        );
      })}
    </div>
  );
}

function TooltipRow({
  label,
  value,
  color,
  volume,
}: {
  label: string;
  value: number;
  color: string;
  volume?: boolean;
}) {
  return (
    <>
      <span style={{ opacity: 0.5 }}>{label}</span>
      <span style={{ fontWeight: 600, color, textAlign: 'right' }}>
        {volume ? formatVolume(value) : value.toFixed(2)}
      </span>
    </>
  );
}

/** Format a volume number with K/M/B suffixes for compact display. */
function formatVolume(v: number): string {
  if (v >= 1e9) return (v / 1e9).toFixed(2) + 'B';
  if (v >= 1e6) return (v / 1e6).toFixed(2) + 'M';
  if (v >= 1e3) return (v / 1e3).toFixed(1) + 'K';
  return v.toFixed(0);
}
