// packages/vue/src/ui/TooltipLegend.vue
<script setup lang="ts">
import { type LineData, type OHLCData, formatTime } from '@wick-charts/core';
import { computed, inject, onMounted, onUnmounted, ref, watch } from 'vue';

import { useCrosshairPosition } from '../composables';
import { ThemeKey, TooltipLegendAnchorKey, useChartInstance } from '../context';

type TooltipSort = 'none' | 'asc' | 'desc';

interface SeriesSnapshot {
  id: string;
  label?: string;
  data: OHLCData | LineData;
  color: string;
}

const props = withDefaults(
  defineProps<{
    seriesId?: string;
    sort?: TooltipSort;
  }>(),
  {
    sort: 'none',
  },
);

const chart = useChartInstance();
const crosshair = useCrosshairPosition(chart);
const theme = inject(ThemeKey);
const anchor = inject(TooltipLegendAnchorKey);

// Match the "loud failure" contract of other Vue overlays — misuse outside
// `<ChartContainer>` should throw rather than render nothing silently.
if (!theme) {
  throw new Error('<TooltipLegend> must be used within <ChartContainer>: missing ThemeKey.');
}
if (!anchor) {
  throw new Error('<TooltipLegend> must be used within <ChartContainer>: missing TooltipLegendAnchorKey.');
}

// `bump` forces targetIds / snapshots to recompute after sibling series
// register. Without this, a TooltipLegend mounted before its series would
// see `getSeriesIds() === []` and stay empty.
const bump = ref(0);
const targetIds = computed(() => {
  void bump.value;
  return props.seriesId ? [props.seriesId] : chart.getSeriesIds();
});

const primaryId = computed(() => targetIds.value[0] ?? '');
const lastY = ref<{ value: number; isLive: boolean } | null>(
  primaryId.value ? chart.getLastValue(primaryId.value) : null,
);
const dataUpdateHandler = () => {
  const id = primaryId.value;
  lastY.value = id ? chart.getLastValue(id) : null;
};
const seriesChangeHandler = () => {
  bump.value++;
};
onMounted(() => {
  chart.on('dataUpdate', dataUpdateHandler);
  chart.on('seriesChange', seriesChangeHandler);
  // Catch-up: a sibling series' mount effect may have registered data in
  // the same synchronous flush, so poke the computed on mount.
  if (chart.getSeriesIds().length > 0) bump.value++;
});
onUnmounted(() => {
  chart.off('dataUpdate', dataUpdateHandler);
  chart.off('seriesChange', seriesChangeHandler);
});
watch(primaryId, () => dataUpdateHandler());

function sortSnapshots(snapshots: SeriesSnapshot[], sort: TooltipSort): SeriesSnapshot[] {
  if (sort === 'none' || snapshots.length <= 1) return snapshots;
  return [...snapshots].sort((a, b) => {
    const av = 'value' in a.data ? (a.data as LineData).value : (a.data as OHLCData).close;
    const bv = 'value' in b.data ? (b.data as LineData).value : (b.data as OHLCData).close;
    return sort === 'asc' ? av - bv : bv - av;
  });
}

function formatVolume(v: number): string {
  if (v >= 1e9) return `${(v / 1e9).toFixed(2)}B`;
  if (v >= 1e6) return `${(v / 1e6).toFixed(2)}M`;
  if (v >= 1e3) return `${(v / 1e3).toFixed(1)}K`;
  return v.toFixed(0);
}

function isOHLC(data: OHLCData | LineData): data is OHLCData {
  return 'open' in data;
}

const snapshots = computed(() => {
  void lastY.value;
  const hover: SeriesSnapshot[] = [];
  if (crosshair.value) {
    const time = crosshair.value.time;
    for (const id of targetIds.value) {
      const layers = chart.getLayerSnapshots(id, time);
      if (layers) {
        for (let i = 0; i < layers.length; i++) {
          hover.push({
            id: `${id}_layer${i}`,
            label: chart.getSeriesLabel(id),
            data: { time, value: layers[i].value } as LineData,
            color: layers[i].color,
          });
        }
        continue;
      }
      const d = chart.getDataAtTime(id, time);
      if (d) hover.push({ id, label: chart.getSeriesLabel(id), data: d, color: chart.getSeriesColor(id) ?? '#888' });
    }
  }
  if (hover.length > 0) return sortSnapshots(hover, props.sort);
  const last: SeriesSnapshot[] = [];
  for (const id of targetIds.value) {
    const d = chart.getLastData(id);
    if (!d) continue;
    const layers = chart.getLayerSnapshots(id, d.time);
    if (layers) {
      for (let i = 0; i < layers.length; i++) {
        last.push({
          id: `${id}_layer${i}`,
          label: chart.getSeriesLabel(id),
          data: { time: d.time, value: layers[i].value } as LineData,
          color: layers[i].color,
        });
      }
      continue;
    }
    last.push({ id, label: chart.getSeriesLabel(id), data: d, color: chart.getSeriesColor(id) ?? '#888' });
  }
  return sortSnapshots(last, props.sort);
});

const dataInterval = computed(() => chart.getDataInterval());
const displayTime = computed(() => (snapshots.value.length === 0 ? 0 : snapshots.value[0].data.time));
</script>

<template>
  <Teleport v-if="anchor && theme && snapshots.length > 0" :to="anchor">
    <div
      data-tooltip-legend=""
      :style="{
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        flexWrap: 'wrap',
        padding: '4px 8px',
        flexShrink: 0,
        fontSize: theme.typography.fontSize + 'px',
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        opacity: crosshair ? 1 : 0.6,
        transition: 'opacity 0.2s ease',
        pointerEvents: 'none',
      }"
    >
      <span :style="{ color: theme.axis.textColor, marginRight: '2px' }">
        {{ formatTime(displayTime, dataInterval) }}
      </span>
      <template v-for="s in snapshots" :key="s.id">
        <span v-if="isOHLC(s.data)" :style="{ display: 'inline-flex', alignItems: 'center', gap: '4px' }">
          <template v-for="field in (['O', 'H', 'L', 'C'] as const)" :key="field">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">{{ field }}</span>
            <span
              :style="{
                color:
                  (s.data as OHLCData).close >= (s.data as OHLCData).open
                    ? theme.candlestick.upColor
                    : theme.candlestick.downColor,
                fontWeight: 500,
                marginLeft: '2px',
              }"
            >
              {{
                (
                  { O: (s.data as OHLCData).open, H: (s.data as OHLCData).high, L: (s.data as OHLCData).low, C: (s.data as OHLCData).close }
                )[field].toFixed(2)
              }}
            </span>
          </template>
          <template v-if="(s.data as OHLCData).volume != null">
            <span :style="{ color: theme.axis.textColor, opacity: 0.5, marginLeft: '5px' }">V</span>
            <span :style="{ color: theme.axis.textColor, fontWeight: 500, marginLeft: '2px' }">
              {{ formatVolume((s.data as OHLCData).volume!) }}
            </span>
          </template>
        </span>
        <span v-else :style="{ display: 'inline-flex', alignItems: 'center', gap: '3px' }">
          <span
            :style="{
              width: '6px',
              height: '6px',
              borderRadius: '50%',
              background: s.color,
              flexShrink: 0,
            }"
          />
          <span :style="{ color: s.color, fontWeight: 500 }">
            {{ (s.data as LineData).value.toFixed(2) }}
          </span>
        </span>
      </template>
    </div>
  </Teleport>
</template>

// packages/react/src/ui/TooltipLegend.tsx
import { useLayoutEffect, useState } from 'react';

import { type OHLCData, type TimePoint, formatTime } from '@wick-charts/core';

import { useChartInstance } from '../context';
import { useCrosshairPosition } from '../store-bridge';
import { useTheme } from '../ThemeContext';
import type { TooltipSort } from './Tooltip';

/** Props for the {@link TooltipLegend} component. */
export interface TooltipLegendProps {
  /** Show only this series. When omitted, show all series. */
  seriesId?: string;
  /** Sort order for line values when showing all series (default: 'none'). */
  sort?: TooltipSort;
}

interface SeriesSnapshot {
  id: string;
  label?: string;
  data: OHLCData | TimePoint;
  color: string;
}

function sortSnapshots(snapshots: SeriesSnapshot[], sort: TooltipSort): SeriesSnapshot[] {
  if (sort === 'none' || snapshots.length <= 1) return snapshots;
  return [...snapshots].sort((a, b) => {
    const av = 'value' in a.data ? (a.data as TimePoint).value : (a.data as OHLCData).close;
    const bv = 'value' in b.data ? (b.data as TimePoint).value : (b.data as OHLCData).close;
    return sort === 'asc' ? av - bv : bv - av;
  });
}

/**
 * Compact OHLC/series info bar rendered as a flex row above the chart canvas.
 * Pairs with {@link Tooltip} (which then only renders its floating near-cursor part).
 * Its presence causes the chart plot area to shrink by the bar's height and the
 * Y-range to recompute — via the same DOM-flex + ResizeObserver path used by {@link Legend}.
 */
export function TooltipLegend({ seriesId, sort = 'none' }: TooltipLegendProps) {
  const chart = useChartInstance();
  const theme = useTheme();
  const crosshair = useCrosshairPosition(chart);

  const targetIds = seriesId ? [seriesId] : chart.getSeriesIds();

  const [, bump] = useState(0);
  useLayoutEffect(() => {
    const onDataUpdate = () => bump((n) => n + 1);
    const onSeriesChange = () => bump((n) => n + 1);
    chart.on('dataUpdate', onDataUpdate);
    chart.on('seriesChange', onSeriesChange);
    // Catch-up: a sibling CandlestickSeries/LineSeries layout effect may have
    // already registered data in this same commit. Bump so the next
    // synchronous render reflects it before paint.
    if (chart.getSeriesIds().length > 0) bump((n) => n + 1);
    return () => {
      chart.off('dataUpdate', onDataUpdate);
      chart.off('seriesChange', onSeriesChange);
    };
  }, [chart]);

  const hoverSnapshots: SeriesSnapshot[] = [];
  if (crosshair) {
    for (const id of targetIds) {
      const layers = chart.getLayerSnapshots(id, crosshair.time);
      if (layers) {
        for (let i = 0; i < layers.length; i++) {
          hoverSnapshots.push({
            id: `${id}_layer${i}`,
            label: chart.getSeriesLabel(id),
            data: { time: crosshair.time, value: layers[i].value } as TimePoint,
            color: layers[i].color,
          });
        }
      } else {
        const d = chart.getDataAtTime(id, crosshair.time);
        if (d)
          hoverSnapshots.push({
            id,
            label: chart.getSeriesLabel(id),
            data: d,
            color: chart.getSeriesColor(id) ?? '#888',
          });
      }
    }
  }

  let raw: SeriesSnapshot[];
  if (hoverSnapshots.length > 0) {
    raw = hoverSnapshots;
  } else {
    const lastSnapshots: SeriesSnapshot[] = [];
    for (const id of targetIds) {
      const d = chart.getLastData(id);
      if (!d) continue;
      const layers = chart.getLayerSnapshots(id, d.time);
      if (layers) {
        for (let i = 0; i < layers.length; i++) {
          lastSnapshots.push({
            id: `${id}_layer${i}`,
            label: chart.getSeriesLabel(id),
            data: { time: d.time, value: layers[i].value } as TimePoint,
            color: layers[i].color,
          });
        }
      } else {
        lastSnapshots.push({ id, label: chart.getSeriesLabel(id), data: d, color: chart.getSeriesColor(id) ?? '#888' });
      }
    }
    raw = lastSnapshots;
  }
  const snapshots = sortSnapshots(raw, sort);
  if (snapshots.length === 0) return null;

  const dataInterval = chart.getDataInterval();
  const displayTime = snapshots[0].data.time;

  return (
    <div
      data-tooltip-legend=""
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        flexWrap: 'wrap',
        padding: '4px 8px',
        flexShrink: 0,
        fontSize: theme.typography.fontSize,
        fontFamily: theme.typography.fontFamily,
        fontVariantNumeric: 'tabular-nums',
        opacity: crosshair ? 1 : 0.6,
        transition: 'opacity 0.2s ease',
        pointerEvents: 'none',
      }}
    >
      <span style={{ color: theme.axis.textColor, marginRight: 2 }}>{formatTime(displayTime, dataInterval)}</span>
      {snapshots.map((s) => {
        const isOHLC = 'open' in s.data;
        if (isOHLC) {
          const ohlc = s.data as OHLCData;
          const isUp = ohlc.close >= ohlc.open;
          const c = isUp ? theme.candlestick.upColor : theme.candlestick.downColor;
          return (
            <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
              <LegendItem label="O" value={ohlc.open} color={c} dim={theme.axis.textColor} />
              <LegendItem label="H" value={ohlc.high} color={c} dim={theme.axis.textColor} />
              <LegendItem label="L" value={ohlc.low} color={c} dim={theme.axis.textColor} />
              <LegendItem label="C" value={ohlc.close} color={c} dim={theme.axis.textColor} />
              {ohlc.volume != null && (
                <LegendItem
                  label="V"
                  value={ohlc.volume}
                  color={theme.axis.textColor}
                  dim={theme.axis.textColor}
                  volume
                />
              )}
            </span>
          );
        }
        const line = s.data as TimePoint;
        return (
          <span key={s.id} style={{ display: 'inline-flex', alignItems: 'center', gap: 3 }}>
            <span
              style={{
                width: 6,
                height: 6,
                borderRadius: '50%',
                background: s.color,
                flexShrink: 0,
              }}
            />
            <span style={{ color: s.color, fontWeight: 500 }}>{line.value.toFixed(2)}</span>
          </span>
        );
      })}
    </div>
  );
}

function LegendItem({
  label,
  value,
  color,
  dim,
  volume,
}: {
  label: string;
  value: number;
  color: string;
  dim: string;
  volume?: boolean;
}) {
  return (
    <>
      <span style={{ color: dim, opacity: 0.5, marginLeft: 5 }}>{label}</span>
      <span style={{ color, fontWeight: 500, marginLeft: 2 }}>{volume ? formatVolume(value) : value.toFixed(2)}</span>
    </>
  );
}

function formatVolume(v: number): string {
  if (v >= 1e9) return (v / 1e9).toFixed(2) + 'B';
  if (v >= 1e6) return (v / 1e6).toFixed(2) + 'M';
  if (v >= 1e3) return (v / 1e3).toFixed(1) + 'K';
  return v.toFixed(0);
}
