// packages/vue/src/BarSeries.vue
<script setup lang="ts">
import type { BarSeriesOptions, TimePoint } from '@wick-charts/core';
import { onMounted, onUnmounted, ref, watch } from 'vue';

import { useChartInstance } from './context';

const props = defineProps<{
  data: TimePoint[][];
  options?: Partial<BarSeriesOptions>;
  label?: string;
  /** Stable series ID — same value across remounts. */
  id?: string;
}>();

const chart = useChartInstance();
const seriesId = ref<string | null>(null);

onMounted(() => {
  const id = chart.addBarSeries({
    ...props.options,
    label: props.label ?? props.options?.label,
    layers: props.data.length,
    id: props.id,
  });
  seriesId.value = id;
  // Lazy watcher — apply initial data here so static-data mounts render without a no-op first frame.
  chart.batch(() => {
    for (let i = 0; i < props.data.length; i++) {
      chart.setSeriesData(id, props.data[i], i);
    }
  });
});

onUnmounted(() => {
  if (seriesId.value) chart.removeSeries(seriesId.value);
});

watch(
  () => props.data,
  (data) => {
    if (!seriesId.value) return;
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setSeriesData(seriesId.value!, data[i], i);
      }
    });
  },
);

watch(
  () => props.options,
  (options) => {
    if (seriesId.value && options) {
      chart.updateSeriesOptions(seriesId.value, options);
    }
  },
  { deep: true },
);
</script>

<template><span v-if="false" /></template>

// packages/svelte/src/BarSeries.svelte
<script lang="ts">
import type { BarSeriesOptions, TimePoint } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from './context';

export let data: TimePoint[][] = [];
export let options: Partial<BarSeriesOptions> | undefined = undefined;
export let label: string | undefined = undefined;
/** Stable series ID — same value across remounts. */
export let id: string | undefined = undefined;

const chartStore = getChartContext();
let seriesId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;
  seriesId = chart.addBarSeries({ ...options, label: label ?? options?.label, layers: data.length, id });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (seriesId && chart) chart.removeSeries(seriesId);
  seriesId = null;
});

$: {
  const chart = $chartStore;
  if (seriesId && chart) {
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setSeriesData(seriesId!, data[i], i);
      }
    });
  }
}

$: {
  const chart = $chartStore;
  if (seriesId && chart && options) {
    chart.updateSeriesOptions(seriesId, options);
  }
}
</script>
