// src/react/BarSeries.tsx
import { useEffect, useRef } from "react";
import type { BarSeriesOptions, LineData } from "../core/types";
import { useChartInstance } from "./context";

export interface BarSeriesProps {
  data: LineData[];
  options?: Partial<BarSeriesOptions>;
  onSeriesId?: (id: string) => void;
}

export function BarSeries({ data, options, onSeriesId }: BarSeriesProps) {
  const chart = useChartInstance();
  const seriesRef = useRef<string | null>(null);
  const prevLenRef = useRef(0);

  useEffect(() => {
    const id = chart.addBarSeries(options);
    seriesRef.current = id;
    onSeriesId?.(id);
    return () => {
      chart.removeSeries(id);
      seriesRef.current = null;
      prevLenRef.current = 0;
    };
  }, [chart]);

  useEffect(() => {
    if (seriesRef.current && options) {
      chart.updateSeriesOptions(seriesRef.current, options);
    }
  }, [chart, options?.positiveColor, options?.negativeColor, options?.barWidthRatio]);

  useEffect(() => {
    const id = seriesRef.current;
    if (!id || data.length === 0) return;

    const prevLen = prevLenRef.current;

    if (prevLen === 0 || data.length < prevLen || data.length - prevLen > 5) {
      chart.setSeriesData(id, data);
    } else if (data.length === prevLen) {
      chart.updateData(id, data[data.length - 1]);
    } else {
      for (let i = prevLen; i < data.length; i++) {
        chart.appendData(id, data[i]);
      }
    }

    prevLenRef.current = data.length;
  }, [chart, data]);

  return null;
}

// packages/svelte/src/BarSeries.svelte
<script lang="ts">
import type { BarSeriesOptions, LineData } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from './context';

export let data: LineData[][] = [];
export let options: Partial<BarSeriesOptions> | undefined = undefined;
export let onSeriesId: ((id: string) => void) | undefined = undefined;

const chartStore = getChartContext();
let seriesId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;
  seriesId = chart.addBarSeries(data.length, options);
  onSeriesId?.(seriesId);
});

onDestroy(() => {
  const chart = get(chartStore);
  if (seriesId && chart) chart.removeSeries(seriesId);
  seriesId = null;
});

$: {
  const chart = $chartStore;
  if (seriesId && chart && data.length > 0) {
    chart.beginUpdate();
    for (let i = 0; i < data.length; i++) {
      chart.setBarLayerData(seriesId, i, data[i]);
    }
    chart.endUpdate();
  }
}

$: {
  const chart = $chartStore;
  if (seriesId && chart && options) {
    chart.updateSeriesOptions(seriesId, options);
  }
}
</script>
