// packages/vue/src/LineSeries.vue
<script setup lang="ts">
import type { LineSeriesOptions, TimePoint } from '@wick-charts/core';
import { onMounted, onUnmounted, ref, watch } from 'vue';

import { useChartInstance } from './context';

const props = defineProps<{
  data: TimePoint[][];
  options?: Partial<LineSeriesOptions>;
  label?: string;
}>();

const emit = defineEmits<{ seriesId: [id: string] }>();

const chart = useChartInstance();
const seriesId = ref<string | null>(null);

onMounted(() => {
  const id = chart.addLineSeries({ ...props.options, label: props.label ?? props.options?.label, layers: props.data.length });
  seriesId.value = id;
  emit('seriesId', id);
});

onUnmounted(() => {
  if (seriesId.value) chart.removeSeries(seriesId.value);
});

watch(
  () => props.data,
  (data) => {
    if (!seriesId.value) return;
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setLineLayerData(seriesId.value!, i, data[i]);
      }
    });
  },
);

watch(
  () => props.options,
  (options) => {
    if (seriesId.value && options) {
      chart.updateSeriesOptions(seriesId.value, options);
    }
  },
  { deep: true },
);
</script>

<template><span v-if="false" /></template>

// packages/svelte/src/LineSeries.svelte
<script lang="ts">
import type { LineSeriesOptions, TimePoint } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from './context';

export let data: TimePoint[][] = [];
export let options: Partial<LineSeriesOptions> | undefined = undefined;
export let label: string | undefined = undefined;
export let onSeriesId: ((id: string) => void) | undefined = undefined;

const chartStore = getChartContext();
let seriesId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;
  seriesId = chart.addLineSeries({ ...options, label: label ?? options?.label, layers: data.length });
  onSeriesId?.(seriesId);
});

onDestroy(() => {
  const chart = get(chartStore);
  if (seriesId && chart) chart.removeSeries(seriesId);
  seriesId = null;
});

$: {
  const chart = $chartStore;
  if (seriesId && chart) {
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setLineLayerData(seriesId!, i, data[i]);
      }
    });
  }
}

$: {
  const chart = $chartStore;
  if (seriesId && chart && options) {
    chart.updateSeriesOptions(seriesId, options);
  }
}
</script>
