// packages/react/src/LineSeries.tsx
import { useEffect, useRef } from 'react';

import type { LineData, LineSeriesOptions } from '@wick-charts/core';
import { useChartInstance } from './context';

export interface LineSeriesProps {
  /** Array of datasets — one per layer. A single line uses `[data]`. */
  data: LineData[][];
  options?: Partial<LineSeriesOptions>;
  label?: string;
  onSeriesId?: (id: string) => void;
}

export function LineSeries({ data, options, label, onSeriesId }: LineSeriesProps) {
  const chart = useChartInstance();
  const seriesRef = useRef<string | null>(null);

  useEffect(() => {
    const id = chart.addLineSeries(data.length, { ...options, label: label ?? options?.label });
    seriesRef.current = id;
    onSeriesId?.(id);
    return () => {
      chart.removeSeries(id);
      seriesRef.current = null;
    };
  }, [chart, data.length]);

  useEffect(() => {
    const id = seriesRef.current;
    if (!id) return;
    for (let i = 0; i < data.length; i++) {
      chart.setLineLayerData(id, i, data[i]);
    }
  }, [chart, data]);

  useEffect(() => {
    if (seriesRef.current && options) {
      chart.updateSeriesOptions(seriesRef.current, options);
    }
  }, [chart, options?.colors?.join(','), options?.lineWidth, options?.areaFill, options?.pulse, options?.stacking]);

  return null;
}

// packages/svelte/src/LineSeries.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { get } from 'svelte/store';
  import type { LineData, LineSeriesOptions } from '@wick-charts/core';
  import { getChartContext } from './context';

  export let data: LineData[][] = [];
  export let options: Partial<LineSeriesOptions> | undefined = undefined;
  export let label: string | undefined = undefined;
  export let onSeriesId: ((id: string) => void) | undefined = undefined;

  const chartStore = getChartContext();
  let seriesId: string | null = null;

  onMount(() => {
    const chart = get(chartStore);
    if (!chart) return;
    seriesId = chart.addLineSeries(data.length, { ...options, label: label ?? options?.label });
    onSeriesId?.(seriesId);
  });

  onDestroy(() => {
    const chart = get(chartStore);
    if (seriesId && chart) chart.removeSeries(seriesId);
    seriesId = null;
  });

  $: {
    const chart = $chartStore;
    if (seriesId && chart && data.length > 0) {
      for (let i = 0; i < data.length; i++) {
        chart.setLineLayerData(seriesId, i, data[i]);
      }
    }
  }

  $: {
    const chart = $chartStore;
    if (seriesId && chart && options) {
      chart.updateSeriesOptions(seriesId, options);
    }
  }
</script>
