// packages/vue/src/PieSeries.vue
<script setup lang="ts">
import type { PieSeriesOptions, PieSliceData } from '@wick-charts/core';
import { onMounted, onUnmounted, ref, watch } from 'vue';

import { useChartInstance } from './context';

const props = defineProps<{
  data: PieSliceData[];
  options?: Partial<PieSeriesOptions>;
}>();

const emit = defineEmits<{ seriesId: [id: string] }>();

const chart = useChartInstance();
const seriesId = ref<string | null>(null);

onMounted(() => {
  const id = chart.addPieSeries(props.options);
  seriesId.value = id;
  emit('seriesId', id);
});

onUnmounted(() => {
  if (seriesId.value) chart.removeSeries(seriesId.value);
});

watch(
  () => props.data,
  (data) => {
    if (seriesId.value && data.length > 0) {
      chart.setPieData(seriesId.value, data);
    }
  },
);

watch(
  () => props.options,
  (options) => {
    if (seriesId.value && options) {
      chart.updateSeriesOptions(seriesId.value, options);
    }
  },
  { deep: true },
);
</script>

<template><span v-if="false" /></template>

// packages/svelte/src/PieSeries.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { get } from 'svelte/store';
  import type { PieSliceData, PieSeriesOptions } from '@wick-charts/core';
  import { getChartContext } from './context';

  export let data: PieSliceData[] = [];
  export let options: Partial<PieSeriesOptions> | undefined = undefined;
  export let onSeriesId: ((id: string) => void) | undefined = undefined;

  const chartStore = getChartContext();
  let seriesId: string | null = null;

  onMount(() => {
    const chart = get(chartStore);
    if (!chart) return;
    seriesId = chart.addPieSeries(options);
    onSeriesId?.(seriesId);
  });

  onDestroy(() => {
    const chart = get(chartStore);
    if (seriesId && chart) chart.removeSeries(seriesId);
    seriesId = null;
  });

  $: {
    const chart = $chartStore;
    if (seriesId && chart && data.length > 0) {
      chart.setPieData(seriesId, data);
    }
  }

  $: {
    const chart = $chartStore;
    if (seriesId && chart && options) {
      chart.updateSeriesOptions(seriesId, options);
    }
  }
</script>
