// packages/svelte/src/BarSeries.svelte
<script lang="ts">
import type { BarSeriesOptions, TimePoint } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from './context';

export let data: TimePoint[][] = [];
export let options: Partial<BarSeriesOptions> | undefined = undefined;
export let label: string | undefined = undefined;
/** Stable series ID — same value across remounts. */
export let id: string | undefined = undefined;

const chartStore = getChartContext();
let seriesId: string | null = null;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;
  seriesId = chart.addBarSeries({ ...options, label: label ?? options?.label, layers: data.length, id });
});

onDestroy(() => {
  const chart = get(chartStore);
  if (seriesId && chart) chart.removeSeries(seriesId);
  seriesId = null;
});

$: {
  const chart = $chartStore;
  if (seriesId && chart) {
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setSeriesData(seriesId!, data[i], i);
      }
    });
  }
}

$: {
  const chart = $chartStore;
  if (seriesId && chart && options) {
    chart.updateSeriesOptions(seriesId, options);
  }
}
</script>

// packages/react/src/BarSeries.tsx
import { useEffect, useLayoutEffect, useRef } from 'react';

import type { BarSeriesOptions, TimePoint } from '@wick-charts/core';

import { useChartInstance } from './context';

export interface BarSeriesProps {
  /** Array of datasets — one per layer. A single-layer bar chart uses `[data]`. */
  data: TimePoint[][];
  options?: Partial<BarSeriesOptions>;
  /** Display label shown in the tooltip. */
  label?: string;
  /** Stable series ID. Prefer this over `onSeriesId` — same value across remounts. */
  id?: string;
  /** @deprecated Use the `id` prop instead. */
  onSeriesId?: (id: string) => void;
}

export function BarSeries({ data, options, label, id: idProp, onSeriesId }: BarSeriesProps) {
  const chart = useChartInstance();
  const seriesRef = useRef<string | null>(null);

  useLayoutEffect(() => {
    const id = chart.addBarSeries({ ...options, label: label ?? options?.label, layers: data.length, id: idProp });
    seriesRef.current = id;
    onSeriesId?.(id);
    return () => {
      chart.removeSeries(id);
      seriesRef.current = null;
    };
  }, [chart, data.length, idProp]);

  useLayoutEffect(() => {
    const id = seriesRef.current;
    if (!id) return;
    chart.batch(() => {
      for (let i = 0; i < data.length; i++) {
        chart.setBarLayerData(id, i, data[i]);
      }
    });
  }, [chart, data]);

  useEffect(() => {
    if (seriesRef.current && options) {
      chart.updateSeriesOptions(seriesRef.current, options);
    }
  }, [chart, options?.colors?.join(','), options?.barWidthRatio, options?.stacking]);

  return null;
}
