// packages/svelte/src/CandlestickSeries.svelte
<script lang="ts">
import type { CandlestickSeriesOptions, OHLCData } from '@wick-charts/core';
import { onDestroy, onMount } from 'svelte';
import { get } from 'svelte/store';

import { getChartContext } from './context';

export let data: OHLCData[] = [];
export let options: Partial<CandlestickSeriesOptions> | undefined = undefined;
export let onSeriesId: ((id: string) => void) | undefined = undefined;

const chartStore = getChartContext();
let seriesId: string | null = null;
let prevLen = 0;

onMount(() => {
  const chart = get(chartStore);
  if (!chart) return;
  seriesId = chart.addCandlestickSeries(options);
  onSeriesId?.(seriesId);
});

onDestroy(() => {
  const chart = get(chartStore);
  if (seriesId && chart) chart.removeSeries(seriesId);
  seriesId = null;
  prevLen = 0;
});

$: {
  const chart = $chartStore;
  const id = seriesId;
  if (id && chart) {
    if (data.length === 0) {
      chart.setSeriesData(id, []);
      prevLen = 0;
    } else if (prevLen === 0 || data.length < prevLen || data.length - prevLen > 5) {
      chart.setSeriesData(id, data);
      prevLen = data.length;
    } else if (data.length === prevLen) {
      chart.updateData(id, data[data.length - 1]);
    } else {
      for (let i = prevLen; i < data.length; i++) {
        chart.appendData(id, data[i]);
      }
      prevLen = data.length;
    }
  }
}

$: {
  const chart = $chartStore;
  if (seriesId && chart && options) {
    chart.updateSeriesOptions(seriesId, options);
  }
}
</script>

// packages/react/src/CandlestickSeries.tsx
import { useEffect, useRef } from 'react';

import type { CandlestickSeriesOptions, OHLCData } from '@wick-charts/core';

import { useChartInstance } from './context';

export interface CandlestickSeriesProps {
  data: OHLCData[];
  options?: Partial<CandlestickSeriesOptions>;
  onSeriesId?: (id: string) => void;
}

export function CandlestickSeries({ data, options, onSeriesId }: CandlestickSeriesProps) {
  const chart = useChartInstance();
  const seriesRef = useRef<string | null>(null);
  const prevLenRef = useRef(0);

  useEffect(() => {
    const id = chart.addCandlestickSeries(options);
    seriesRef.current = id;
    onSeriesId?.(id);
    return () => {
      chart.removeSeries(id);
      seriesRef.current = null;
      prevLenRef.current = 0;
    };
  }, [chart]);

  useEffect(() => {
    const id = seriesRef.current;
    if (!id || data.length === 0) return;

    const prevLen = prevLenRef.current;

    if (prevLen === 0 || data.length < prevLen || data.length - prevLen > 5) {
      // First load, reset, or batch — full replace
      chart.setSeriesData(id, data);
    } else if (data.length === prevLen) {
      // Same length — last candle updated
      chart.updateData(id, data[data.length - 1]);
    } else {
      // Small append (1-5 new candles)
      for (let i = prevLen; i < data.length; i++) {
        chart.appendData(id, data[i]);
      }
    }

    prevLenRef.current = data.length;
  }, [chart, data]);

  return null;
}
