// packages/svelte/src/PieSeries.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { get } from 'svelte/store';
  import type { PieSliceData, PieSeriesOptions } from '@wick-charts/core';
  import { getChartContext } from './context';

  export let data: PieSliceData[] = [];
  export let options: Partial<PieSeriesOptions> | undefined = undefined;
  export let onSeriesId: ((id: string) => void) | undefined = undefined;

  const chartStore = getChartContext();
  let seriesId: string | null = null;

  onMount(() => {
    const chart = get(chartStore);
    if (!chart) return;
    seriesId = chart.addPieSeries(options);
    onSeriesId?.(seriesId);
  });

  onDestroy(() => {
    const chart = get(chartStore);
    if (seriesId && chart) chart.removeSeries(seriesId);
    seriesId = null;
  });

  $: {
    const chart = $chartStore;
    if (seriesId && chart && data.length > 0) {
      chart.setPieData(seriesId, data);
    }
  }

  $: {
    const chart = $chartStore;
    if (seriesId && chart && options) {
      chart.updateSeriesOptions(seriesId, options);
    }
  }
</script>

// packages/react/src/PieSeries.tsx
import { useEffect, useRef } from 'react';

import type { PieSeriesOptions, PieSliceData } from '@wick-charts/core';
import { useChartInstance } from './context';

export interface PieSeriesProps {
  data: PieSliceData[];
  options?: Partial<PieSeriesOptions>;
  onSeriesId?: (id: string) => void;
}

/** Pie chart series. Set `options.innerRadiusRatio` > 0 for donut. */
export function PieSeries({ data, options, onSeriesId }: PieSeriesProps) {
  const chart = useChartInstance();
  const seriesRef = useRef<string | null>(null);

  useEffect(() => {
    const id = chart.addPieSeries(options);
    seriesRef.current = id;
    onSeriesId?.(id);
    return () => {
      chart.removeSeries(id);
      seriesRef.current = null;
    };
  }, [chart]);

  useEffect(() => {
    if (seriesRef.current && options) {
      chart.updateSeriesOptions(seriesRef.current, options);
    }
  }, [chart, options?.innerRadiusRatio, options?.padAngle, options?.strokeColor, options?.strokeWidth, options?.colors]);

  useEffect(() => {
    if (seriesRef.current && data.length > 0) {
      chart.setPieData(seriesRef.current, data);
    }
  }, [chart, data]);

  return null;
}
