// packages/svelte/src/ChartContainer.svelte
<script lang="ts">
import {
  type AnimationsConfig,
  type AxisConfig,
  ChartInstance,
  type ChartOptions,
  type ChartTheme,
  type CrosshairPosition,
  type EdgeReachedInfo,
  type PointClickInfo,
  type SeriesHoverInfo,
  type VisibleRange,
  type VisibleRangeSpec,
  catppuccin,
  deepEqual,
} from '@wick-charts/core';
import { onDestroy, onMount, tick } from 'svelte';

import {
  initChartContext,
  initInfoBarAnchor,
  initLegendAnchor,
  initLegendRightAnchor,
  initNavigatorAnchor,
  initThemeContext,
  initTitleAnchor,
} from './context';

type PerfOption = NonNullable<ChartOptions['perf']>;

/** Visual theme. Live — changing this at runtime updates all themed elements. */
export let theme: ChartTheme = catppuccin.theme;
/** Grouped axis configuration (Y/X visibility, bounds, sizing). Live. */
export let axis: AxisConfig | undefined = undefined;
/**
 * Viewport padding. `top`/`bottom` are in pixels. `left`/`right` accept either pixels (`50`)
 * or data intervals (`{ intervals: 3 }`). Set to 0 for edge-to-edge sparklines. Updates are
 * applied reactively when this prop or the measured header height changes.
 * Defaults: `{ top: 20, bottom: 20, right: { intervals: 3 }, left: { intervals: 0 } }`.
 */
// biome-ignore format: keep the inline shape so the parity checker matches React's type string verbatim
export let padding: { top?: number; bottom?: number; right?: number | { intervals: number }; left?: number | { intervals: number }; } | undefined = undefined;
/**
 * Viewport-level streaming behavior. Captured at mount only — changing
 * this prop after the chart is created is ignored.
 */
export let viewport: { maxVisibleBars?: number; initialRange?: VisibleRangeSpec } | undefined = undefined;
/**
 * Controlled visible range. Same shape as the imperative
 * `chart.setVisibleRange` — a bar count, an explicit `{from, to}` window, or
 * `{from, bars}`. Every reference/value change applies via
 * `chart.setVisibleRange`, so pair it with `onVisibleRangeChange` for a
 * two-way binding; a same-value literal (compared structurally) is a no-op,
 * so an inline object doesn't re-apply on every render.
 *
 * For a one-shot initial window that isn't re-applied on every prop change,
 * use `viewport.initialRange` instead.
 */
export let visibleRange: VisibleRangeSpec | undefined = undefined;
/** Show the chart background gradient. Live. Defaults to true. */
export let gradient: boolean = true;
/**
 * Enable zoom, pan, and crosshair interactions. Defaults to true.
 *
 * Mount-only — core has no `setInteractive`, so changing this prop after
 * mount is ignored.
 */
export let interactive: boolean | undefined = undefined;
/** Background grid configuration. Live. Default: `{ visible: true }`. */
export let grid: { visible: boolean } | undefined = undefined;
/**
 * How `<Title>` and `<InfoBar>` are positioned relative to the canvas. Live.
 * - `'overlay'` (default): absolute overlays on top of the canvas.
 * - `'inline'`: flex siblings above the canvas — the canvas (and grid) shift down.
 */
export let headerLayout: 'overlay' | 'inline' = 'overlay';
/**
 * Animation control. `true` / omitted uses built-in defaults; `false`
 * disables every category. Per-series options on `<LineSeries>` /
 * `<CandlestickSeries>` / `<BarSeries>` override these chart-level
 * defaults unless the category here is explicitly `false`.
 *
 * **Init-only, but diffed by value, not reference.** A same-value inline
 * object literal is a no-op — only a genuine change to the resolved config
 * recreates the underlying `ChartInstance`, since the animation engine
 * doesn't support live reconfiguration yet.
 */
export let animations: boolean | AnimationsConfig | undefined = undefined;
/**
 * Enable runtime performance instrumentation. Off by default. Read at mount only;
 * later changes are ignored.
 */
export let perf: PerfOption | undefined = undefined;
/**
 * Fired after the user releases a pan/zoom gesture that pulled the viewport
 * past a data edge by more than ~10% of the visible range. Hosts typically
 * respond by prefetching more history. Captured at mount only; changing
 * the prop identity later is ignored.
 */
export let onEdgeReached: ((info: EdgeReachedInfo) => void) | undefined = undefined;
/**
 * Fired on a click (or tap) on the chart canvas that isn't the tail end of a
 * pan drag. `info.spatialHit` resolves a pie/heatmap/custom-spatial series
 * directly under the pointer; for a time-series series, resolve the point
 * yourself from `info.time` (`chart.getDataAtTime` / `buildHoverSnapshots`).
 * Live — the latest callback is always used.
 */
export let onPointClick: ((info: PointClickInfo) => void) | undefined = undefined;
/**
 * Fired on a double-click on the chart canvas. The chart also responds by
 * calling `fitContent()`. Live — the latest callback is always used.
 */
export let onPointDoubleClick: ((info: PointClickInfo) => void) | undefined = undefined;
/**
 * Fired when the spatially-hovered series/index changes (pie, heatmap, or a
 * custom spatial kind) — `null` when the pointer leaves every hit area.
 * Live — the latest callback is always used.
 */
export let onSeriesHover: ((hit: SeriesHoverInfo | null) => void) | undefined = undefined;
/**
 * Fired once the underlying `ChartInstance` is constructed — on mount, and
 * again if the chart is ever rebuilt (a genuine `animations` value change).
 * Live — the latest callback is always used for the next rebuild.
 */
export let onReady: ((chart: ChartInstance) => void) | undefined = undefined;
/**
 * Fired whenever the committed visible range changes — pan, zoom,
 * `fitContent()`, a data update that shifts the tail-scroll window, or a
 * `visibleRange` prop change. Live — the latest callback is always used.
 */
export let onVisibleRangeChange: ((range: VisibleRange) => void) | undefined = undefined;
/**
 * Fired on every crosshair move, with `null` when the pointer leaves the
 * chart. Live — the latest callback is always used.
 */
export let onCrosshairMove: ((position: CrosshairPosition | null) => void) | undefined = undefined;
/** Inline style for the chart's outer wrapper element. Live. */
export let style: string = '';

let containerEl: HTMLDivElement;
let topOverlayEl: HTMLDivElement | null = null;
let titleAnchorEl: HTMLDivElement;
let infoBarAnchorEl: HTMLDivElement;
let legendAnchorEl: HTMLDivElement;
let legendRightAnchorEl: HTMLDivElement;
let navigatorAnchorEl: HTMLDivElement;

const chartStore = initChartContext();
const themeStore = initThemeContext(theme);
const titleAnchorStore = initTitleAnchor();
const infoBarAnchorStore = initInfoBarAnchor();
const legendAnchorStore = initLegendAnchor();
const legendRightAnchorStore = initLegendRightAnchor();
const navigatorAnchorStore = initNavigatorAnchor();

let instance: ChartInstance | null = null;
let resizeObserver: ResizeObserver | null = null;
let topOverlayHeight = 0;

// Inline mode: browser flex already reserves header height, so folding it
// into padding.top would double-shift the data. Only overlay needs the fold.
$: headerExtra = headerLayout === 'overlay' ? topOverlayHeight : 0;

function applyPadding() {
  if (!instance) return;

  const userTop = padding?.top ?? 20;
  const merged: ChartOptions['padding'] = { top: userTop + headerExtra };
  if (padding?.bottom !== undefined) merged.bottom = padding.bottom;
  if (padding?.right !== undefined) merged.right = padding.right;
  if (padding?.left !== undefined) merged.left = padding.left;
  instance.setPadding(merged);
}

// Capture perf at mount only — mirror React's perfRef so a later change of
// object identity doesn't recreate the chart.
const perfAtMount = perf;
// Same mount-only capture for the edge callback — the chart binds it once.
const onEdgeReachedAtMount = onEdgeReached;

// Wires up (or tears down) the header-height observer for the current
// `headerLayout`. Called on mount AND whenever `headerLayout` flips at
// runtime — overlay needs a live measurement; inline lets browser flex
// layout reserve the height directly.
function syncHeaderObserver() {
  resizeObserver?.disconnect();
  resizeObserver = null;

  const headerEl = headerLayout === 'overlay' ? topOverlayEl : null;
  if (!headerEl) {
    // Reset stale measurement so the next applyPadding call drops back to
    // the user's configured `padding.top` instead of carrying inline-mode
    // height.
    topOverlayHeight = 0;
    applyPadding();

    return;
  }

  const measure = () => {
    topOverlayHeight = headerEl.getBoundingClientRect().height;
    applyPadding();
  };
  measure();
  resizeObserver = new ResizeObserver(measure);
  resizeObserver.observe(headerEl);
}

// Read the exported `let` directly (not a frozen mount-time const) so each
// call sees the caller's latest callback, mirroring Vue's reactive-props
// read. Shared between the mount path and the animations-triggered rebuild
// below so the two don't drift.
function subscribeDeclarativeEvents(target: ChartInstance): void {
  target.on('pointClick', (info) => onPointClick?.(info));
  target.on('pointDoubleClick', (info) => onPointDoubleClick?.(info));
  target.on('seriesHover', (hit) => onSeriesHover?.(hit));
  target.on('crosshairMove', (position) => onCrosshairMove?.(position));
  const emitVisibleRangeChange = () => onVisibleRangeChange?.(target.getVisibleRange());
  target.on('viewportChange', emitVisibleRangeChange);
  target.on('dataUpdate', emitVisibleRangeChange);
  target.on('seriesChange', emitVisibleRangeChange);
}

onMount(() => {
  const options: ChartOptions = {};
  if (axis) options.axis = axis;
  if (theme) options.theme = theme;
  if (padding) options.padding = padding;
  if (viewport) options.viewport = viewport;
  if (interactive !== undefined) options.interactive = interactive;
  if (grid !== undefined) options.grid = grid;
  if (perfAtMount !== undefined) options.perf = perfAtMount;
  if (onEdgeReachedAtMount) options.onEdgeReached = onEdgeReachedAtMount;
  if (animations !== undefined) options.animations = animations;
  instance = new ChartInstance(containerEl, options);
  chartStore.set(instance);
  subscribeDeclarativeEvents(instance);
  onReady?.(instance);

  void tick().then(() => {
    titleAnchorStore.set(titleAnchorEl);
    infoBarAnchorStore.set(infoBarAnchorEl);
    legendAnchorStore.set(legendAnchorEl);
    legendRightAnchorStore.set(legendRightAnchorEl);
    navigatorAnchorStore.set(navigatorAnchorEl);
    syncHeaderObserver();
  });
});

// Re-attach the observer when `headerLayout` toggles after mount, so an
// overlay → inline → overlay round-trip keeps measuring the new header.
let lastHeaderLayout = headerLayout;
$: if (instance && headerLayout !== lastHeaderLayout) {
  lastHeaderLayout = headerLayout;
  void tick().then(syncHeaderObserver);
}

onDestroy(() => {
  resizeObserver?.disconnect();
  resizeObserver = null;
  instance?.destroy();
  instance = null;
  chartStore.set(null);
  titleAnchorStore.set(null);
  infoBarAnchorStore.set(null);
  legendAnchorStore.set(null);
  legendRightAnchorStore.set(null);
  navigatorAnchorStore.set(null);
});

$: if (instance && theme) {
  instance.setTheme(theme);
  themeStore.set(theme);
}

$: if (instance && axis) {
  instance.setAxis(axis);
}

$: if (instance && grid !== undefined) {
  instance.setGrid(grid);
}

// Init-only: a post-mount `animations` VALUE change tears down the instance
// and rebuilds with the new config. `deepEqual` (not reference equality)
// gates the rebuild — a caller's brand-new inline literal with the same
// values is a no-op, since Svelte re-runs this reactive block on every
// reference change regardless of content.
//
// Children inside the `{#if $chartStore}` block grab the chart store
// snapshot in their own setup. To force them to re-mount against the
// new ChartInstance, push `null` through the store first — the
// `{#if}` guard tears down the slot — then `await tick()` so Svelte
// commits the unmount before the new instance is constructed. Setting
// the store to the new instance re-mounts children, who re-read the
// current chart in their fresh setup.
let lastAnimations = animations;
async function rebuildChartFromAnimations() {
  if (!instance || !containerEl) return;
  instance.destroy();
  instance = null;
  chartStore.set(null);
  await tick();
  const opts: ChartOptions = {};
  if (axis) opts.axis = axis;
  if (theme) opts.theme = theme;
  if (padding) opts.padding = padding;
  if (viewport) opts.viewport = viewport;
  if (interactive !== undefined) opts.interactive = interactive;
  if (grid !== undefined) opts.grid = grid;
  if (perfAtMount !== undefined) opts.perf = perfAtMount;
  if (onEdgeReachedAtMount) opts.onEdgeReached = onEdgeReachedAtMount;
  if (animations !== undefined) opts.animations = animations;
  instance = new ChartInstance(containerEl, opts);
  subscribeDeclarativeEvents(instance);
  chartStore.set(instance);
  onReady?.(instance);
}
$: if (instance && !deepEqual(animations, lastAnimations)) {
  lastAnimations = animations;
  rebuildChartFromAnimations();
}

// Controlled visible range: only re-apply when the resolved value actually
// differs from what we last applied ourselves, so feeding the range from
// `onVisibleRangeChange` back into this prop (the standard two-way-binding
// shape) doesn't re-trigger `setVisibleRange` with an unchanged spec on
// every render.
let lastAppliedVisibleRange: VisibleRangeSpec | undefined;
async function applyControlledVisibleRange(target: ChartInstance, next: VisibleRangeSpec) {
  lastAppliedVisibleRange = next;
  // On the chart's first tick, a series child (e.g. `<CandlestickSeries>`)
  // hasn't mounted and seeded its data yet, so the engine is still on the
  // placeholder `dataInterval` (60s) — a `{from, to}` spec sized for the
  // real interval would fail the 2-bar-minimum guard. Awaiting a tick lets
  // the child's data-seed (and its `detectInterval` call) land first.
  await tick();
  target.setVisibleRange(next);
}
$: if (instance && visibleRange !== undefined && !deepEqual(lastAppliedVisibleRange, visibleRange)) {
  applyControlledVisibleRange(instance, visibleRange);
}

// Re-apply padding on any input that affects it — including `headerExtra`,
// so a runtime `headerLayout` toggle re-folds the measured header height
// even when the consumer never passes an explicit `padding` prop.
$: if (instance) {
  void padding;
  void headerExtra;
  applyPadding();
}

$: gradientBg = (() => {
  const t = theme;
  const [gtop, gbot] = t?.chartGradient ?? ['transparent', 'transparent'];
  const bg = t?.background ?? 'transparent';

  return gradient ? `linear-gradient(to bottom, ${gtop} 0%, ${bg} 70%, ${gbot} 100%)` : bg;
})();
</script>

<div
  {style}
  style:position="relative"
  style:display="flex"
  style:flex-direction="column"
  style:width="100%"
  style:height="100%"
  style:min-height="240px"
  style:overflow="hidden"
  style:background={gradientBg}
>
  <div style="display:flex;flex-direction:row;flex:1;min-height:0">
    <div style="display:flex;flex-direction:column;flex:1;min-width:0;min-height:0">
      {#if headerLayout === 'inline'}
        <div
          data-chart-header=""
          style="flex-shrink:0;display:flex;flex-direction:column;pointer-events:none"
        >
          <div bind:this={titleAnchorEl} data-chart-title-anchor=""></div>
          <div bind:this={infoBarAnchorEl} data-tooltip-legend-anchor=""></div>
        </div>
      {/if}
      <div
        bind:this={containerEl}
        style="position:relative;flex:1;min-width:0;min-height:0;overflow:hidden"
      >
        {#if headerLayout === 'overlay'}
          <div
            bind:this={topOverlayEl}
            data-chart-top-overlay=""
            style="position:absolute;top:0;left:0;right:0;z-index:2;pointer-events:none;display:flex;flex-direction:column"
          >
            <div bind:this={titleAnchorEl} data-chart-title-anchor=""></div>
            <div bind:this={infoBarAnchorEl} data-tooltip-legend-anchor=""></div>
          </div>
        {/if}
        {#if $chartStore}
          <div
            data-chart-series-overlay=""
            style="position:absolute;inset:0;pointer-events:none;z-index:3"
          >
            <slot />
          </div>
        {/if}
      </div>
    </div>
    <div bind:this={legendRightAnchorEl} data-legend-right-anchor="" style="flex:0 0 auto"></div>
  </div>
  <div bind:this={legendAnchorEl} data-legend-anchor="" style="flex:0 0 auto"></div>
  <div bind:this={navigatorAnchorEl} data-navigator-anchor="" style="flex:0 0 auto"></div>
</div>

// packages/vue/src/ChartContainer.vue
<script setup lang="ts">
import {
  type AnimationsConfig,
  type AxisConfig,
  ChartInstance,
  type ChartOptions,
  type ChartTheme,
  type CrosshairPosition,
  type EdgeReachedInfo,
  type PointClickInfo,
  type SeriesHoverInfo,
  type VisibleRange,
  type VisibleRangeSpec,
  catppuccin,
  deepEqual,
} from '@wick-charts/core';
import { computed, nextTick, onMounted, onUnmounted, provide, ref, shallowRef, watch } from 'vue';

import {
  ChartKey,
  InfoBarAnchorKey,
  LegendAnchorKey,
  LegendRightAnchorKey,
  NavigatorAnchorKey,
  ThemeKey,
  TitleAnchorKey,
} from './context';

type PerfOption = NonNullable<ChartOptions['perf']>;

const props = withDefaults(
  defineProps<{
    theme?: ChartTheme;
    axis?: AxisConfig;
    /**
     * Viewport padding. `top`/`bottom` are in pixels. `left`/`right` accept either pixels (`50`)
     * or data intervals (`{ intervals: 3 }`). Set to 0 for edge-to-edge sparklines. Updates are
     * applied reactively when this prop or the measured header height changes.
     * Defaults: `{ top: 20, bottom: 20, right: { intervals: 3 }, left: { intervals: 0 } }`.
     */
    padding?: {
      top?: number;
      bottom?: number;
      right?: number | { intervals: number };
      left?: number | { intervals: number };
    };
    /**
     * Viewport-level streaming behavior. Captured at mount only — changing
     * this prop after the chart is created is ignored.
     */
    viewport?: {
      /**
       * Width of the visible window in data bars, set on the first data load
       * to `maxVisibleBars * dataInterval`. While the dataset is smaller than
       * this width, streaming ticks render into the empty right-side gap and
       * the viewport stays put; once the data reaches the right edge, the
       * viewport pans forward to keep the latest bar pinned (tail-scroll).
       * Default: 200.
       */
      maxVisibleBars?: number;
      /**
       * Initial visible range applied before the first paint with data. Same
       * shape as the imperative `chart.setVisibleRange` — pass a bar count
       * (e.g. `35`), an explicit `{from, to}` window, or `{from, bars}` for
       * a warm-up pair. Captured at mount.
       */
      initialRange?: VisibleRangeSpec;
    };
    /**
     * Controlled visible range. Same shape as the imperative
     * `chart.setVisibleRange` — a bar count, an explicit `{from, to}` window,
     * or `{from, bars}`. Every reference/value change applies via
     * `chart.setVisibleRange`, so pair it with `onVisibleRangeChange` for a
     * two-way binding; a same-value literal (compared structurally) is a
     * no-op, so an inline object doesn't re-apply on every render.
     *
     * For a one-shot initial window that isn't re-applied on every prop
     * change, use `viewport.initialRange` instead.
     */
    visibleRange?: VisibleRangeSpec;
    /** Show the chart background gradient. Defaults to true. */
    gradient?: boolean;
    /** Enable zoom, pan, and crosshair interactions. Defaults to true. */
    interactive?: boolean;
    /** Background grid configuration. Default: `{ visible: true }`. */
    grid?: { visible: boolean };
    /**
     * How `<Title>` and `<InfoBar>` are positioned relative to the canvas.
     * - `'overlay'` (default): absolute overlays on top of the canvas.
     * - `'inline'`: flex siblings above the canvas — the canvas (and grid) shift down.
     */
    headerLayout?: 'overlay' | 'inline';
    /**
     * Animation control. `true` / omitted uses built-in defaults; `false`
     * disables every category. Per-series options on `<LineSeries>` /
     * `<CandlestickSeries>` / `<BarSeries>` override these chart-level
     * defaults unless the category here is explicitly `false`.
     *
     * **Init-only, but diffed by value, not reference.** A same-value
     * inline object literal is a no-op — only a genuine change to the
     * resolved config recreates the underlying `ChartInstance`, since the
     * animation engine doesn't support live reconfiguration yet.
     */
    animations?: boolean | AnimationsConfig;
    /**
     * Enable runtime performance instrumentation. Off by default. Read at mount only;
     * later changes are ignored.
     */
    perf?: PerfOption;
    /**
     * Fired after the user releases a pan/zoom gesture that pulled the viewport
     * past a data edge by more than ~10% of the visible range. Hosts typically
     * respond by prefetching more history. Captured at mount only; changing
     * the prop identity later is ignored.
     */
    onEdgeReached?: (info: EdgeReachedInfo) => void;
    /**
     * Fired on a click (or tap) on the chart canvas that isn't the tail end
     * of a pan drag. `info.spatialHit` resolves a pie/heatmap/custom-spatial
     * series directly under the pointer; for a time-series series, resolve
     * the point yourself from `info.time` (`chart.getDataAtTime` /
     * `buildHoverSnapshots`). Live — the latest callback is always used.
     */
    onPointClick?: (info: PointClickInfo) => void;
    /**
     * Fired on a double-click on the chart canvas. The chart also responds
     * by calling `fitContent()`. Live — the latest callback is always used.
     */
    onPointDoubleClick?: (info: PointClickInfo) => void;
    /**
     * Fired when the spatially-hovered series/index changes (pie, heatmap,
     * or a custom spatial kind) — `null` when the pointer leaves every hit
     * area. Live — the latest callback is always used.
     */
    onSeriesHover?: (hit: SeriesHoverInfo | null) => void;
    /**
     * Fired once the underlying `ChartInstance` is constructed — on mount,
     * and again if the chart is ever rebuilt (a genuine `animations` value
     * change). Live — the latest callback is always used for the next rebuild.
     */
    onReady?: (chart: ChartInstance) => void;
    /**
     * Fired whenever the committed visible range changes — pan, zoom,
     * `fitContent()`, a data update that shifts the tail-scroll window, or a
     * `visibleRange` prop change. Live — the latest callback is always used.
     */
    onVisibleRangeChange?: (range: VisibleRange) => void;
    /**
     * Fired on every crosshair move, with `null` when the pointer leaves the
     * chart. Live — the latest callback is always used.
     */
    onCrosshairMove?: (position: CrosshairPosition | null) => void;
  }>(),
  {
    theme: () => catppuccin.theme,
    gradient: true,
    // Vue's type-based `defineProps` casts an absent Boolean-typed prop to
    // `false` (not `undefined`) — without this explicit default, every chart
    // that didn't pass `:interactive="true"` silently got zero pan/zoom/
    // crosshair/click interactivity. `gradient` dodges the same trap only
    // because it already had a default.
    interactive: true,
    headerLayout: 'overlay',
  },
);

const containerRef = ref<HTMLDivElement>();
const chart = shallowRef<ChartInstance | null>(null);
const themeRef = shallowRef<ChartTheme>(props.theme);

// Capture perf at mount only — mirrors React's perfRef so a new object
// identity later doesn't recreate the chart.
const perfAtMount = props.perf;
// Same mount-only capture for the edge callback — the chart binds it once.
const onEdgeReachedAtMount = props.onEdgeReached;

const topOverlayRef = ref<HTMLElement | null>(null);
const titleAnchor = ref<HTMLElement | null>(null);
const infoBarAnchor = ref<HTMLElement | null>(null);
const legendAnchor = ref<HTMLElement | null>(null);
const legendRightAnchor = ref<HTMLElement | null>(null);
const navigatorAnchor = ref<HTMLElement | null>(null);

provide(ChartKey, chart);
provide(ThemeKey, themeRef);
provide(TitleAnchorKey, titleAnchor);
provide(InfoBarAnchorKey, infoBarAnchor);
provide(LegendAnchorKey, legendAnchor);
provide(LegendRightAnchorKey, legendRightAnchor);
provide(NavigatorAnchorKey, navigatorAnchor);

let resizeObserver: ResizeObserver | null = null;
const topOverlayHeight = ref(0);

// Inline mode: browser flex already reserves header height, so folding it
// into padding.top would double-shift the data. Only overlay needs the fold.
const headerExtra = computed(() => (props.headerLayout === 'overlay' ? topOverlayHeight.value : 0));

function applyPadding() {
  if (!chart.value) return;
  const userTop = props.padding?.top ?? 20;
  const merged: ChartOptions['padding'] = { top: userTop + headerExtra.value };
  if (props.padding?.bottom !== undefined) merged.bottom = props.padding.bottom;
  if (props.padding?.right !== undefined) merged.right = props.padding.right;
  if (props.padding?.left !== undefined) merged.left = props.padding.left;
  chart.value.setPadding(merged);
}

// Wires up (or tears down) the header-height observer for the current
// `headerLayout`. Called on mount AND whenever `headerLayout` flips at
// runtime — overlay needs a live measurement, inline lets browser flex
// layout reserve the height directly.
function syncHeaderObserver() {
  resizeObserver?.disconnect();
  resizeObserver = null;

  const headerEl = props.headerLayout === 'overlay' ? topOverlayRef.value : null;
  if (!headerEl) {
    // Reset stale measurement so the next applyPadding call drops back to the
    // user's configured `padding.top` instead of carrying inline-mode height.
    topOverlayHeight.value = 0;
    applyPadding();

    return;
  }

  const measure = () => {
    topOverlayHeight.value = headerEl.getBoundingClientRect().height;
    applyPadding();
  };
  measure();
  resizeObserver = new ResizeObserver(measure);
  resizeObserver.observe(headerEl);
}

// `props` is a reactive proxy — reading `props.onX` inside these listeners
// always sees the caller's latest callback, no ref-latch needed the way
// React does. Shared between the mount path and the animations-triggered
// rebuild below so the two don't drift.
function subscribeDeclarativeEvents(instance: ChartInstance): void {
  instance.on('pointClick', (info) => props.onPointClick?.(info));
  instance.on('pointDoubleClick', (info) => props.onPointDoubleClick?.(info));
  instance.on('seriesHover', (hit) => props.onSeriesHover?.(hit));
  instance.on('crosshairMove', (position) => props.onCrosshairMove?.(position));
  const emitVisibleRangeChange = () => props.onVisibleRangeChange?.(instance.getVisibleRange());
  instance.on('viewportChange', emitVisibleRangeChange);
  instance.on('dataUpdate', emitVisibleRangeChange);
  instance.on('seriesChange', emitVisibleRangeChange);
}

onMounted(async () => {
  if (!containerRef.value) return;

  const options: ChartOptions = {};
  if (props.axis) options.axis = props.axis;
  if (props.theme) options.theme = props.theme;
  if (props.padding) options.padding = props.padding;
  if (props.viewport) options.viewport = props.viewport;
  if (props.interactive !== undefined) options.interactive = props.interactive;
  if (props.grid !== undefined) options.grid = props.grid;
  if (perfAtMount !== undefined) options.perf = perfAtMount;
  if (onEdgeReachedAtMount) options.onEdgeReached = onEdgeReachedAtMount;
  if (props.animations !== undefined) options.animations = props.animations;
  chart.value = new ChartInstance(containerRef.value, options);
  subscribeDeclarativeEvents(chart.value);
  props.onReady?.(chart.value);

  await nextTick();
  syncHeaderObserver();
});

onUnmounted(() => {
  resizeObserver?.disconnect();
  resizeObserver = null;
  chart.value?.destroy();
  chart.value = null;
});

// Re-attach the observer when `headerLayout` toggles after mount, so an
// overlay → inline → overlay round-trip keeps measuring the new header.
watch(
  () => props.headerLayout,
  async () => {
    if (!chart.value) return;
    await nextTick();
    syncHeaderObserver();
  },
);

watch(
  () => props.theme,
  (newTheme) => {
    if (chart.value && newTheme) {
      chart.value.setTheme(newTheme);
      themeRef.value = newTheme;
    }
  },
);

watch(
  () => props.axis,
  (newAxis) => {
    if (chart.value && newAxis) chart.value.setAxis(newAxis);
  },
  { deep: true },
);

watch(
  () => props.grid?.visible,
  () => {
    if (chart.value && props.grid !== undefined) chart.value.setGrid(props.grid);
  },
);

// Init-only: a post-mount `animations` VALUE change tears down the instance
// and rebuilds with the new config. `deepEqual` (not reference equality)
// gates the rebuild — a caller's brand-new inline literal with the same
// values is a no-op, since Vue's `watch` fires this callback on every
// reference change regardless of content.
//
// Children get the chart via `useChartInstance()` which snapshots
// `chartRef.value` once at setup time. To force them to re-setup against
// the new instance, we flip `chart.value` to `null` first — the `v-if`
// guard in the template unmounts the slot — then `await nextTick()` so
// Vue commits the unmount before the new ChartInstance is constructed.
// When `chart.value` becomes the new instance, the slot re-mounts and
// every child's `setup()` runs again against the fresh chart.
let lastAnimations = props.animations;
watch(
  () => props.animations,
  async (next) => {
    if (deepEqual(next, lastAnimations)) return;
    lastAnimations = next;
    if (!chart.value || !containerRef.value) return;
    chart.value.destroy();
    chart.value = null;
    await nextTick();
    const opts: ChartOptions = {};
    if (props.axis) opts.axis = props.axis;
    if (props.theme) opts.theme = props.theme;
    if (props.padding) opts.padding = props.padding;
    if (props.viewport) opts.viewport = props.viewport;
    if (props.interactive !== undefined) opts.interactive = props.interactive;
    if (props.grid !== undefined) opts.grid = props.grid;
    if (perfAtMount !== undefined) opts.perf = perfAtMount;
    if (onEdgeReachedAtMount) opts.onEdgeReached = onEdgeReachedAtMount;
    if (next !== undefined) opts.animations = next;
    chart.value = new ChartInstance(containerRef.value, opts);
    subscribeDeclarativeEvents(chart.value);
    props.onReady?.(chart.value);
  },
);

// Controlled visible range: only re-apply when the resolved value actually
// differs from what we last applied ourselves, so feeding the range from
// `onVisibleRangeChange` back into this prop (the standard two-way-binding
// shape) doesn't re-trigger `setVisibleRange` with an unchanged spec on
// every render.
let lastAppliedVisibleRange: VisibleRangeSpec | undefined;
watch(
  () => [chart.value, props.visibleRange] as const,
  async ([instance, next]) => {
    if (!instance || next === undefined) return;
    if (deepEqual(lastAppliedVisibleRange, next)) return;

    lastAppliedVisibleRange = next;
    // On the chart's first tick, a series child (e.g. `<CandlestickSeries>`)
    // hasn't mounted and seeded its data yet, so the engine is still on the
    // placeholder `dataInterval` (60s) — a `{from, to}` spec sized for the
    // real interval would fail the 2-bar-minimum guard. Awaiting a tick lets
    // the child's data-seed (and its `detectInterval` call) land first.
    await nextTick();
    instance.setVisibleRange(next);
  },
  { immediate: true },
);

// Re-apply padding on any input that affects it — including `headerExtra`,
// so a runtime `headerLayout` toggle re-runs even when `padding` is undefined
// (the default top=20 still needs the fold-in/out).
watch(
  () => [
    props.padding?.top,
    props.padding?.bottom,
    typeof props.padding?.right === 'object' ? props.padding.right.intervals : props.padding?.right,
    typeof props.padding?.left === 'object' ? props.padding.left.intervals : props.padding?.left,
    headerExtra.value,
  ],
  applyPadding,
);

const rootStyle = computed(() => {
  const t = themeRef.value;
  const [gtop, gbot] = t?.chartGradient ?? ['transparent', 'transparent'];
  const bg = t?.background ?? 'transparent';
  const background = props.gradient ? `linear-gradient(to bottom, ${gtop} 0%, ${bg} 70%, ${gbot} 100%)` : bg;

  return (
    'position: relative; display: flex; flex-direction: column; width: 100%; height: 100%; min-height: 240px; overflow: hidden; ' +
    `background: ${background}`
  );
});
</script>

<template>
  <div :style="rootStyle">
    <div style="display: flex; flex-direction: row; flex: 1; min-height: 0">
      <!-- Canvas-block column. In inline mode the header is a flex sibling
           above the canvas inside this column; in overlay mode it's absolute
           over the canvas (rendered inside `containerRef`). -->
      <div style="display: flex; flex-direction: column; flex: 1; min-width: 0; min-height: 0">
        <div
          v-if="headerLayout === 'inline'"
          data-chart-header=""
          style="flex-shrink: 0; display: flex; flex-direction: column; pointer-events: none"
        >
          <div ref="titleAnchor" data-chart-title-anchor="" />
          <div ref="infoBarAnchor" data-tooltip-legend-anchor="" />
        </div>
        <div
          ref="containerRef"
          style="position: relative; flex: 1; min-width: 0; min-height: 0; overflow: hidden"
        >
          <div
            v-if="headerLayout === 'overlay'"
            ref="topOverlayRef"
            data-chart-top-overlay=""
            style="position: absolute; top: 0; left: 0; right: 0; z-index: 2; pointer-events: none; display: flex; flex-direction: column"
          >
            <div ref="titleAnchor" data-chart-title-anchor="" />
            <div ref="infoBarAnchor" data-tooltip-legend-anchor="" />
          </div>
          <div
            v-if="chart"
            data-chart-series-overlay=""
            style="position: absolute; inset: 0; pointer-events: none; z-index: 3"
          >
            <slot />
          </div>
        </div>
      </div>
      <div ref="legendRightAnchor" data-legend-right-anchor="" style="flex: 0 0 auto" />
    </div>
    <div ref="legendAnchor" data-legend-anchor="" style="flex: 0 0 auto" />
    <div ref="navigatorAnchor" data-navigator-anchor="" style="flex: 0 0 auto" />
  </div>
</template>
